import test from 'node:test';
import assert from 'node:assert/strict';
import {Game} from '../src/engine.js';
import {emptyLevel,validateLevel} from '../src/levels.js';
import {alarmSummary} from '../src/alarms.js';
const link={switchId:'A',on:true,delay:1.5};
const gun={type:'turret',x:12,y:4,dir:'right',period:2,phase:0,speed:200,alarm:link};
function harness(patch={}){const g=Object.create(Game.prototype);g.keys=new Set();g.render=()=>{};g.cb={hud(){},sound(){},dead(){},win(){}};g.load({...emptyLevel(),version:3,width:32,height:18,switches:[{id:'A',x:25,y:15,mode:'toggle'},{id:'B',x:27,y:15}],devices:[gun],...patch});g.start();return g;}
function step(g,n){for(let i=0;i<n;i++)g.update(1/120);}
test('alarm-linked hazards stay dormant until their circuit matches',()=>{const g=harness();step(g,600);assert.equal(g.devices[0].state,'dormant');assert.equal(g.projectiles.length,0);assert.match(alarmSummary(g),/!A ON: QUIET/);});
test('late activation starts a fresh warning and firing cycle without catching up old shots',()=>{const g=harness();step(g,617);g.activated.add('A');step(g,1);const start=g.devices[0].alarmStart;assert.equal(start,g.clock);step(g,150);assert.equal(g.devices[0].state,'arming');assert.equal(g.projectiles.length,0);step(g,50);assert.equal(g.projectiles.length,0);step(g,230);assert.equal(g.projectiles.length,1);assert.ok(g.clock-start>=3.5);});
test('turning an alarm off cancels it; reactivation gives the full warning again',()=>{const g=harness();g.activated.add('A');step(g,100);g.activated.delete('A');step(g,1);assert.equal(g.devices[0].state,'dormant');assert.equal(g.devices[0].alarmStart,null);g.activated.add('A');step(g,1);const start=g.clock;step(g,100);assert.equal(g.devices[0].state,'arming');assert.equal(g.devices[0].alarmStart,start);assert.equal(g.devices[0].alarmActivations,2);});
test('OFF-state alarm groups warn on initial load and silence when the lever turns ON',()=>{const g=harness({devices:[{...gun,alarm:{...link,on:false}}]});assert.equal(g.devices[0].state,'arming');assert.equal(g.devices[0].alarmStart,0);g.activated.add('A');step(g,1);assert.equal(g.devices[0].state,'dormant');g.load(g.level);assert.equal(g.devices[0].state,'arming');assert.equal(g.devices[0].alarmActivations,1);});
test('freeze and survey preserve the startup countdown',()=>{const g=harness();g.activated.add('A');step(g,60);g.activate('freeze');const clock=g.clock,text=alarmSummary(g),elapsed=g.elapsed;step(g,180);assert.equal(g.clock,clock);assert.equal(alarmSummary(g),text);assert.ok(g.elapsed>elapsed+1);g.effects.freeze=0;g.openMap();step(g,180);assert.equal(g.clock,clock);g.closeMap();step(g,180);assert.notEqual(g.devices[0].state,'arming');});
test('shutdown overrides an alarm without recalling bullets; releasing it warns again',()=>{const g=harness({devices:[{...gun,offSwitch:'B'}]});g.activated.add('A');step(g,430);assert.equal(g.projectiles.length,1);g.activated.add('B');step(g,1);assert.equal(g.devices[0].state,'disabled');assert.equal(g.projectiles.length,1);g.activated.delete('B');step(g,1);assert.equal(g.devices[0].state,'arming');assert.equal(g.devices[0].alarmStart,g.clock);});
test('an alarmed laser stays harmless throughout startup even with a late firing phase',()=>{const g=harness({devices:[{type:'laser',x:5,y:15,dir:'left',length:4,period:4,on:1,phase:3.5,alarm:link}]});g.activated.add('A');step(g,150);assert.equal(g.status,'playing');assert.equal(g.devices[0].state,'arming');step(g,40);assert.equal(g.status,'dying');});
test('sentries need their full lock after the alarm warning',()=>{const g=harness({devices:[],sentries:[{x:12,y:8,range:18,lock:1.2,cooldown:2,speed:220,alarm:link}]});g.activated.add('A');step(g,160);assert.equal(g.sentries[0].charge,0);step(g,100);assert.equal(g.sentries[0].shots,0);step(g,80);assert.equal(g.sentries[0].shots,1);});
test('standing on a dormant plate still gets both alarm and trap warnings before spikes deploy',()=>{const g=harness({devices:[],traps:[{type:'spikes',x:2,y:15,tx:9,ty:15,w:3,delay:1,active:1,cooldown:2,alarm:link}]});step(g,60);assert.equal(g.traps[0].triggers,0);g.activated.add('A');step(g,160);assert.equal(g.traps[0].state,'arming');step(g,40);assert.equal(g.traps[0].state,'warning');step(g,130);assert.equal(g.traps[0].state,'active');});
test('timer expiry quiets every linked hazard and HUD groups repeated links',()=>{const g=harness({switches:[{id:'A',x:25,y:15,mode:'timed',duration:2}],devices:[gun,{...gun,x:18}]});g.activated.add('A');g.switchTimers.A=g.clock+2;step(g,1);assert.equal(alarmSummary(g).split('!A').length,2);step(g,250);assert.ok(g.devices.every(d=>d.state==='dormant'));assert.match(alarmSummary(g),/QUIET/);});
test('alarm schema preserves links and rejects malformed or dangling conditions',()=>{const g=harness();assert.deepEqual(validateLevel(g.level).devices[0].alarm,link);for(const patch of [{switchId:'Z'},{on:'true'},{delay:.5},{delay:5}])assert.throws(()=>validateLevel({...g.level,devices:[{...gun,alarm:{...link,...patch}}]}));});

test('drawing every alarm state is read-only and does not depend on simulation-local variables',async()=>{
 const {drawDevices}=await import('../src/devices.js'),{drawSentries}=await import('../src/sentries.js'),{drawTraps}=await import('../src/traps.js'),{drawAlarmLinks}=await import('../src/alarms.js');
 const g=harness({devices:[gun,{type:'laser',x:8,y:8,dir:'right',length:8,period:4,on:1,phase:0,alarm:link}],sentries:[{x:15,y:8,range:18,lock:1.2,cooldown:2,speed:220,alarm:link}],traps:[{type:'spikes',x:5,y:15,tx:9,ty:15,w:3,delay:1,active:1,cooldown:2,alarm:link}]});
 const context=new Proxy({},{get:(obj,key)=>key in obj?obj[key]:(()=>{}),set:(obj,key,value)=>{obj[key]=value;return true;}});
 for(const state of ['dormant','arming','idle','warning','active','tracking','disabled']){for(const h of [...g.devices,...g.sentries,...g.traps]){h.state=state;h.alarmStart=0;}const before=JSON.stringify([g.devices,g.sentries,g.traps]);drawDevices(context,g);drawSentries(context,g);drawTraps(context,g);drawAlarmLinks(context,g);assert.equal(JSON.stringify([g.devices,g.sentries,g.traps]),before);}
});
