import test from 'node:test';import assert from 'node:assert/strict';
import {openStore} from '../server/store.mjs';import {createInvite,register,login} from '../server/auth.mjs';import {createApp} from '../server/app.mjs';import {generate,reserve,budget,DEFAULT_MODEL} from '../server/ai.mjs';import {draftFromGrid,analyzeLevel} from '../src/level-analysis.js';
const grid=Array.from({length:18},(_,y)=>y===0||y===17?'#'.repeat(32):'#'+'.'.repeat(30)+'#');grid[16]='#.S' + '.'.repeat(26)+'E.#';
const draft={name:'A route',rationale:'Test the full route before publishing.',grid};
const modelResponse=()=>Response.json({data:[{id:DEFAULT_MODEL,pricing:{prompt:'0',completion:'0'}}]});
async function account(db,name='Runner'){return register(db,{name,password:'long-secret-password',invite:createInvite(db)});}
test('invites are one-use, passwords are hashed, and login rejects wrong credentials',async()=>{const db=openStore();try{const invite=createInvite(db),user=await register(db,{name:'Runner',password:'long-secret-password',invite});assert.notEqual(db.prepare('SELECT password FROM users').get().password,'long-secret-password');await assert.rejects(register(db,{name:'Other',password:'long-secret-password',invite}),/Invitation/);await assert.rejects(login(db,{name:'Runner',password:'wrong'}),/incorrect/);assert.equal((await login(db,{name:'Runner',password:'long-secret-password'})).id,user.id);}finally{db.close();}});
test('AI allowance reserves requests atomically, is idempotent, limits concurrency and has no paid fallback',async()=>{const db=openStore();try{const user=await account(db),other=await account(db,'Other'),config={dailyDollars:1,dailyRequests:2,userDailyRequests:1};const first=reserve(db,config,user,'request-0000000001',DEFAULT_MODEL);assert.equal(reserve(db,config,user,'request-0000000001',DEFAULT_MODEL).id,first.id);assert.throws(()=>reserve(db,config,user,'request-0000000002',DEFAULT_MODEL),/allowance/);assert.throws(()=>reserve(db,config,other,'request-0000000003','paid/model'),/free NVIDIA/);assert.equal(budget(db,config,user).requests,1);assert.throws(()=>reserve(db,{dailyDollars:0},other,'request-0000000003',DEFAULT_MODEL),/allowance/);}finally{db.close();}});
test('generation validates drafts and records cost/tokens without resubmitting duplicate requests',async()=>{const db=openStore();try{const user=await account(db);let calls=0;const fetcher=async(url,options)=>{calls++;if(url.endsWith('/models'))return modelResponse();const request=JSON.parse(options.body);assert.equal(request.provider.max_price.prompt,0);assert.equal(request.provider.allow_fallbacks,false);return Response.json({usage:{cost:0,total_tokens:500},choices:[{finish_reason:'stop',message:{content:JSON.stringify(draft)}}]});};const input={prompt:'A fair puzzle with a safe return route.',requestKey:'request-0000000001'};const job=await generate(db,{key:'test'},user,input,fetcher);assert.equal(job.status,'done',job.error);assert.equal(job.result.analysis.status,'unverified');assert.equal(job.tokens,500);assert.equal((await generate(db,{key:'test'},user,input,fetcher)).id,job.id);assert.equal(calls,2);}finally{db.close();}});
test('invalid drafts and provider errors never silently retry or claim proven playability',async()=>{const db=openStore();try{const user=await account(db);let calls=0;const job=await generate(db,{key:'test'},user,{prompt:'A short puzzle.',requestKey:'request-0000000001'},async url=>{calls++;return url.endsWith('/models')?modelResponse():Response.json({choices:[{message:{content:'{"grid":[]}'}}]});});assert.equal(job.status,'failed');assert.equal(calls,2);assert.equal(budget(db,{},user).requests,1);}finally{db.close();}});
test('optimistic connectivity rejects a sealed objective but never proves a jump route',()=>{const {level}=draftFromGrid(draft);assert.equal(analyzeLevel(level).status,'unverified');for(let y=1;y<17;y++)level.tiles.push({x:20,y,type:'solid'});assert.equal(analyzeLevel(level).status,'fail');});
test('HTTP access requires invitation/session, blocks hostile origins and kids community, logs out securely',async()=>{const db=openStore(),origin='https://bnb.minizap.online',server=createApp(db,{});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}`;try{
 const request=(path,options={})=>fetch(url+path,options);
 assert.equal((await request('/v1/ai/config',{headers:{Origin:origin}})).status,401);
 assert.equal((await request('/v1/me',{headers:{Origin:'https://evil.example'}})).status,403);
 assert.equal((await request('/v1/me',{headers:{Origin:'https://kids-bnb.minizap.online'}})).status,403);
 const input={name:'Runner',password:'long-secret-password',invite:createInvite(db)};
 assert.equal((await request('/v1/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)})).status,403);
 const response=await request('/v1/register',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json','X-BNB-Client':'1'},body:JSON.stringify(input)});assert.equal(response.status,200);const cookie=response.headers.get('set-cookie');assert.match(cookie,/HttpOnly/);assert.match(cookie,/Secure/);assert.match(cookie,/SameSite=Strict/);
 const headers={Origin:origin,Cookie:cookie.split(';')[0],'Content-Type':'application/json','X-BNB-Client':'1'};assert.equal((await (await request('/v1/me',{headers})).json()).user.name,'Runner');assert.equal((await request('/v1/invites',{method:'POST',headers})).status,403);await request('/v1/logout',{method:'POST',headers});assert.equal((await (await request('/v1/me',{headers})).json()).user,null);
 }finally{await new Promise(r=>server.close(r));db.close();}});
test('changed pricing blocks the provider call; unexpected charges disable subsequent generation',async()=>{const db=openStore();try{const user=await account(db);let calls=0;const priced=await generate(db,{key:'test'},user,{prompt:'A safe jumping route.',requestKey:'request-pricing-0001'},async()=>{calls++;return Response.json({data:[{id:DEFAULT_MODEL,pricing:{prompt:'1',completion:'0'}}]});});assert.equal(priced.status,'failed');assert.equal(calls,1);
const charged=await generate(db,{key:'test'},user,{prompt:'A safe jumping route.',requestKey:'request-pricing-0002'},async url=>url.endsWith('/models')?modelResponse():Response.json({usage:{cost:.01,total_tokens:5},choices:[]}));assert.equal(charged.status,'failed');assert.equal(charged.costDollars,.01);assert.throws(()=>reserve(db,{},user,'request-pricing-0003',DEFAULT_MODEL),/disabled/);}finally{db.close();}});
test('coordinate blueprints produce validated levels and revision input rejects unsupported mechanics',async()=>{
 const {draftFromBlueprint,blueprintFromLevel}=await import('../src/level-analysis.js');const base=draftFromBlueprint({name:'Coordinates',rationale:'A recoverable route.',spawn:{x:2,y:16},exit:{x:29,y:16},platforms:[{x:5,y:14,w:4}],coins:[{x:5,y:13}],switches:[{id:'A',x:8,y:13}]}).level;
 assert.equal(base.exitRequires[0],'A');assert.equal(blueprintFromLevel(base).platforms[0].w,4);assert.throws(()=>blueprintFromLevel({...base,width:48}),/32 × 18/);assert.throws(()=>draftFromBlueprint({name:'Invalid',rationale:'x',platforms:[{x:30,y:10,w:5}]}),/fit inside/);
});
