import test from 'node:test';import assert from 'node:assert/strict';import {openStore} from '../server/store.mjs';import {createInvite,register,session} from '../server/auth.mjs';import {createApp} from '../server/app.mjs';import {publishLevel,publishSet,communityRoute} from '../server/community.mjs';import {emptyLevel} from '../src/levels.js';
async function fixture(){const db=openStore(),owner=await register(db,{name:'Owner',password:'long-password-owner',invite:createInvite(db,'admin')}),member=await register(db,{name:'Member',password:'long-password-member',invite:createInvite(db)}),server=createApp(db,{extraRoute:communityRoute});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`,cookies=new Map([[owner.id,session(db,owner)],[member.id,session(db,member)]]);return {db,owner,member,async request(path,user=member,data){const response=await fetch(base+path,{method:data?'POST':'GET',headers:{Origin:'https://bnb.minizap.online','Content-Type':'application/json','X-BNB-Client':'1',Cookie:`bnb_session=${cookies.get(user.id)}`},...(data?{body:JSON.stringify(data)}:{})});return {status:response.status,data:await response.json()};},async close(){await new Promise(r=>server.close(r));db.close();}};}
const input=()=>({level:emptyLevel(),description:'A shared route.',difficulty:'medium',tags:['jump'],license:'MIT'});
test('published revisions and set order remain immutable; only authors can revise',async()=>{const f=await fixture();try{const a=publishLevel(f.db,f.owner,input()),b=publishLevel(f.db,f.owner,{...input(),level:{...emptyLevel(),name:'Second room'},parentId:a.id});assert.notEqual(a.id,b.id);assert.equal(JSON.parse(f.db.prepare('SELECT content FROM levels WHERE id=?').get(a.id).content).name,'My first escape');assert.throws(()=>publishLevel(f.db,f.member,{...input(),parentId:a.id}),/Only the author/);const set=publishSet(f.db,f.member,{name:'Ordered challenge',levelIds:[b.id,a.id]});assert.deepEqual(set.levelIds,[b.id,a.id]);assert.throws(()=>publishSet(f.db,f.member,{name:'Repeated',levelIds:[a.id,a.id]}),/distinct/);}finally{await f.close();}});
test('votes replace rather than multiply; bookmarks/search/report/moderation use account boundaries',async()=>{const f=await fixture();try{const item=publishLevel(f.db,f.owner,input()),path=`/v1/community/level/${item.id}`;
assert.equal((await f.request(path+'/vote',f.owner,{value:1})).status,400);await f.request(path+'/vote',f.member,{value:1});await f.request(path+'/vote',f.member,{value:-1});let detail=await f.request(path);assert.equal(detail.data.score,-1);assert.equal(detail.data.votes,1);
await f.request(path+'/bookmark',f.member,{saved:true});const list=await f.request('/v1/community/browse?bookmarks=1&q=shared');assert.equal(list.data.items.length,1);assert.equal((await f.request('/v1/community/browse?q=%25')).data.items.length,0);
await f.request(path+'/report',f.member,{reason:'The route appears blocked.'});assert.equal((await f.request('/v1/community/reports',f.member)).status,403);assert.equal((await f.request('/v1/community/reports',f.owner)).data.reports.length,1);assert.equal((await f.request(path+'/hide',f.member,{})).status,403);await f.request(path+'/hide',f.owner,{});assert.equal((await f.request(path)).status,404);await f.request(path+'/hide',f.owner,{restore:true});assert.equal((await f.request(path)).status,200);
}finally{await f.close();}});
test('attempt completion is owned, single-use and clearly separate from ranked results',async()=>{const f=await fixture();try{const item=publishLevel(f.db,f.owner,input()),path=`/v1/community/level/${item.id}`;const play=await f.request(path+'/play',f.member,{});const finish=`/v1/community/plays/${play.data.playId}`;assert.equal((await f.request(finish,f.owner,{outcome:'completed'})).status,404);assert.equal((await f.request(finish,f.member,{outcome:'completed'})).status,200);assert.equal((await f.request(finish,f.member,{outcome:'completed'})).status,404);assert.equal((await f.request(path)).data.plays.completed,1);}finally{await f.close();}});
test('account export/delete retain no password/session secrets and hide publications',async()=>{const f=await fixture();try{const item=publishLevel(f.db,f.member,input());const exported=await f.request('/v1/account/export');assert.equal(JSON.stringify(exported.data).includes('password'),false);assert.equal(exported.data.levels.length,1);assert.equal((await f.request('/v1/account/delete',f.member,{password:'wrong'})).status,403);assert.equal((await f.request('/v1/account/delete',f.member,{password:'long-password-member'})).status,200);assert.equal((await f.request('/v1/community/browse')).status,401);assert.equal((await f.request(`/v1/community/level/${item.id}`,f.owner)).status,404);assert.equal((await f.request('/v1/account/delete',f.owner,{password:'long-password-owner'})).status,409);}finally{await f.close();}});
