import test from 'node:test';import assert from 'node:assert/strict';import {openStore} from '../server/store.mjs';import {createInvite,register} from '../server/auth.mjs';import {publishLevel,publishSet} from '../server/community.mjs';import {createCompetition,startAttempt,submitRun,competition} from '../server/competitions.mjs';import {emptyLevel} from '../src/levels.js';import {createTape,recordTick} from '../src/replay.js';
async function setup(){const db=openStore(),user=await register(db,{name:'Runner',password:'long-password-runner',invite:createInvite(db)}),level=publishLevel(db,user,{level:emptyLevel(),description:'route',difficulty:'medium',license:'MIT'}),set=publishSet(db,user,{name:'Race set',levelIds:[level.id]});return {db,user,level,set};}
test('events freeze revisions/rules; attempts enforce windows, order, clock and ownership',async()=>{const {db,user,set,level}=await setup(),now=Date.now();try{const event=createCompetition(db,user,{name:'Daily race',setId:set.id,difficulty:'hard',assistance:'itemFree',opens:now,closes:now+3600000,duration:600},now);assert.equal(event.snapshot[0].hash,level.hash);assert.equal(event.rules.difficulty,'hard');assert.throws(()=>startAttempt(db,user,event,now-1),/outside/);const attempt=startAttempt(db,user,event,now);assert.equal(startAttempt(db,user,event,now+1).id,attempt.id);const tape=createTape();recordTick(tape,1,false);
 await assert.rejects(submitRun(db,user,attempt.id,{position:1,levelHash:level.hash,replay:tape},now+2000),/order/);
 const input={position:0,levelHash:level.hash,replay:tape};const fakeVerifier=async()=>({ok:true,ticks:1200,time:10});await assert.rejects(submitRun(db,user,attempt.id,input,now+1000,fakeVerifier),/server attempt clock/);assert.equal(db.prepare('SELECT checking FROM attempts').get().checking,0);
 const result=await submitRun(db,user,attempt.id,input,now+11000,fakeVerifier);assert.equal(result.attempt.status,'completed');assert.equal(result.attempt.total_ms,11000);assert.equal((await submitRun(db,user,attempt.id,input,now+12000,fakeVerifier)).duplicate,true);assert.equal(db.prepare('SELECT COUNT(*) n FROM attempt_runs').get().n,1);
 db.prepare("UPDATE levels SET status='hidden' WHERE id=?").run(level.id);assert.equal(competition(db,event.id).snapshot[0].hash,level.hash);
 }finally{db.close();}});
test('malformed or rejected replays cannot advance an attempt and expired attempts cannot submit',async()=>{const {db,user,set,level}=await setup(),now=Date.now();try{const event=createCompetition(db,user,{name:'Short race',setId:set.id,difficulty:'medium',assistance:'assisted',opens:now,closes:now+60000,duration:60},now),attempt=startAttempt(db,user,event,now);const input={position:0,levelHash:level.hash,replay:{}};await assert.rejects(submitRun(db,user,attempt.id,input,now+1000,async()=>({ok:false,error:'No finish'})),/No finish/);assert.equal(db.prepare('SELECT progress FROM attempts').get().progress,0);await assert.rejects(submitRun(db,user,attempt.id,input,now+60001),/ended/);}finally{db.close();}});
