import test from 'node:test';import assert from 'node:assert/strict';import {Game} from '../src/engine.js';import {endlessChunk,endlessLevel,initEndless,updateEndless,endlessResult,saveEndlessBest,MOTIFS,CHUNK_PX} from '../src/endless.js';
function game(difficulty='medium'){const g=Object.create(Game.prototype);g.keys=new Set();g.render=()=>{};g.burst=()=>{};g.difficulty=difficulty;g.cb={hud(){},sound(){},gold(){},switch(){},win(){throw Error('Endless has no exit');},dying(){},dead(){}};g.die=function(cause){this.status='dead';this.deathCause=cause;};return g;}
// Fixtures use actual collision, acceleration and jump physics; no teleportation or helpers.
for(const difficulty of ['easy','medium','hard'])for(const kind of MOTIFS)test(`${difficulty}: ${kind} motif has a real no-helper crossing`,()=>{const g=game(difficulty),level=endlessLevel('test'),chunks=[endlessChunk('test',0,kind),endlessChunk('test',1,'rest')];level.tiles=chunks.flatMap(c=>c.tiles);level.coins=[];level.width=48;g.load(level);g.start();g.input('ArrowRight',true);const triggers={rest:[],hurdle:[220],gap:[230],spike:[220],steps:[160],double:[130,400]}[kind];let next=0;
 for(let tick=0;tick<720&&g.status==='playing'&&g.player.x<740;tick++){if(next<triggers.length&&g.player.x>=triggers[next]&&g.player.ground){g.input('Space',true);next++;}else g.input('Space',false);g.update(1/120);}
 assert.equal(g.status,'playing',`${kind} failed at x=${g.player.x}, y=${g.player.y}`);assert.ok(g.player.x>=740,`stuck at ${g.player.x}`);assert.equal(g.usedItems,false);
});
test('seeded motifs and clear connectors are stable across a thousand chunks',()=>{for(let seed=0;seed<10;seed++)for(let i=0;i<100;i++){const c=endlessChunk(seed,i);assert.deepEqual(c,endlessChunk(seed,i));for(const local of [0,1,2,3,20,21,22,23]){assert.ok(c.tiles.some(t=>t.x===i*24+local&&t.y===16&&t.type==='solid'));assert.ok(!c.tiles.some(t=>t.x===i*24+local&&t.y<16));}if(i<2||i%5===0)assert.equal(c.kind,'rest');}assert.notDeepEqual(endlessChunk('one',9),endlessChunk('two',9));});
test('streaming retains a bounded window, never edits upcoming geometry, and advances smoothly',()=>{const g=game();initEndless(g,{seed:'stream'});g.start();const first=g.level.tiles.filter(t=>t.x>=72);let previousFire=g.endless.fire,max=0;for(let i=0;i<120*600;i++){g.player.x+=265/120;updateEndless(g,1/120,false);assert.ok(g.endless.fire>=previousFire);assert.ok(g.endless.fire-previousFire<=420/120+1e-8);previousFire=g.endless.fire;max=Math.max(max,g.solids.length);if(i===100)assert.deepEqual(g.level.tiles.filter(t=>t.x>=72&&t.x<120),first);}assert.ok(max<500,`solids ${max}`);assert.ok(g.level.tiles.length<500);assert.equal(g.solidGrid.size,g.solids.length);assert.ok(g.endless.first>200);assert.ok(g.player.x<g.worldW-CHUNK_PX*3);});
test('pause and time freeze stop pursuit, fire kills, retry reproduces seed and resets progress',()=>{const g=game();initEndless(g,{seed:'again',difficulty:'hard',assisted:true});const tiles=structuredClone(g.level.tiles);g.start();g.update(1/120);const x=g.endless.fire;g.togglePause();g.update(5);assert.equal(g.endless.fire,x);g.togglePause();g.effects.freeze=1;g.update(.1);assert.equal(g.endless.fire,x);g.endless.fire=g.player.x;g.update(1/120);assert.equal(g.deathCause,'pursuit');initEndless(g,{...g.endless});assert.deepEqual(g.level.tiles,tiles);assert.equal(g.endless.distance,0);assert.equal(g.collected,0);assert.equal(g.exitUnlocked,false);g.cycleMap();assert.equal(g.mapOpen,false);});
test('local endless records split identities, cap history, and do not downgrade a best',()=>{const data=new Map(),storage={getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)};const g=game();initEndless(g,{seed:'best'});g.player.x=397;g.endless.distance=300;const r=endlessResult(g);assert.equal(saveEndlessBest(storage,r),300);assert.equal(saveEndlessBest(storage,{...r,distance:100}),300);saveEndlessBest(storage,{...r,assisted:true});saveEndlessBest(storage,{...r,difficulty:'hard'});assert.equal(JSON.parse(data.get('endless-bests')).length,3);for(let i=0;i<70;i++)saveEndlessBest(storage,{...r,seed:String(i)});assert.equal(JSON.parse(data.get('endless-bests')).length,50);g.load(endlessLevel('normal'));assert.equal(g.endless,null);});
for(const difficulty of ['easy','medium','hard'])test(`${difficulty}: fifty streamed chunks cross with actual physics, including all seams`,()=>{const g=game();initEndless(g,{seed:'seam-trial',difficulty});g.start();g.input('ArrowRight',true);let index=-1,next=0,triggers=[];for(let tick=0;tick<20000&&g.status==='playing'&&g.player.x<CHUNK_PX*50;tick++){const current=Math.floor(g.player.x/CHUNK_PX);if(current!==index){index=current;next=0;triggers={rest:[],hurdle:[220],gap:[230],spike:[220],steps:[160],double:[130,400]}[endlessChunk('seam-trial',index).kind];}if(next<triggers.length&&g.player.x-index*CHUNK_PX>=triggers[next]&&g.player.ground){g.input('Space',true);next++;}else g.input('Space',false);g.update(1/120);}assert.equal(g.status,'playing',`failed chunk ${index}, ${g.deathCause}, x=${g.player.x}`);assert.ok(g.player.x>=CHUNK_PX*50);assert.ok(g.solids.length<500);assert.equal(g.usedItems,false);});
