import test from 'node:test';
import assert from 'node:assert/strict';
import {Game} from '../src/engine.js';
import {emptyLevel,validateLevel} from '../src/levels.js';
import {lineOfSight} from '../src/sentries.js';
import {updateCrumbles} from '../src/crumbles.js';
const eye={x:12,y:8,range:18,lock:1.2,cooldown:1.5,speed:250};
function harness(patch={}){const g=Object.create(Game.prototype);g.keys=new Set();g.render=()=>{};g.cb={hud(){},sound(){},dead(){},win(){}};g.load({...emptyLevel(),version:3,width:32,height:18,sentries:[eye],...patch});g.start();return g;}
function stand(g,x){Object.assign(g.player,{x:x*30+7,y:454,vx:0,vy:0,ground:true});}
function step(g,n){for(let i=0;i<n;i++)g.update(1/120);}
test('sentry visibly locks before firing at the current player position',()=>{const g=harness();stand(g,5);step(g,100);assert.equal(g.sentries[0].state,'tracking');assert.equal(g.projectiles.length,0);assert.ok(g.sentries[0].charge>.8);stand(g,6);step(g,50);assert.equal(g.sentries[0].shots,1);assert.equal(g.sentries[0].state,'cooldown');const b=g.projectiles[0];assert.ok(b.vx<0&&b.vy>0);assert.ok(Math.abs(Math.hypot(b.vx,b.vy)-250)<1e-8);const velocity=[b.vx,b.vy];stand(g,20);step(g,2);assert.deepEqual([g.projectiles[0].vx,g.projectiles[0].vy],velocity);});
test('static cover breaks a partial lock rather than merely suspending it',()=>{const level=emptyLevel();const g=harness({tiles:[...level.tiles,...Array.from({length:6},(_,i)=>({x:9,y:10+i,type:'solid'}))]});stand(g,15);step(g,70);assert.ok(g.sentries[0].charge>.5);stand(g,5);step(g,1);assert.equal(g.sentries[0].charge,0);assert.equal(g.sentries[0].lostLocks,1);stand(g,15);step(g,100);assert.equal(g.sentries[0].shots,0);});
test('out of range players are not tracked',()=>{const g=harness({sentries:[{...eye,range:6}]});stand(g,2);step(g,300);assert.equal(g.sentries[0].acquisitions,0);assert.equal(g.sentries[0].shots,0);});
test('a diagonal sight ray cannot skip a corner wall cell',()=>{const g=harness({tiles:[...emptyLevel().tiles,{x:9,y:9,type:'solid'}]});assert.equal(lineOfSight(g,255,255,315,315),false);assert.equal(lineOfSight(g,255,240,315,240),true);});
test('closed gates and moving decks block sight; opened gates do not',()=>{const g=harness({switches:[{id:'A',x:25,y:15}],gates:[{switchId:'A',x:10,y:5,w:1,h:8}]});assert.equal(lineOfSight(g,100,200,500,200),false);g.activated.add('A');assert.equal(lineOfSight(g,100,200,500,200),true);g.platforms.push({x:250,y:180,w:120,h:12});assert.equal(lineOfSight(g,300,100,300,300),false);});
test('crumbling cover stops hiding the player after collapse',()=>{const g=harness({crumbles:[{x:8,y:13,w:4,delay:1}]});assert.equal(lineOfSight(g,315,75,315,465),false);g.crumbles[0].startedAt=0;g.clock=2;updateCrumbles(g);assert.equal(lineOfSight(g,315,75,315,465),true);});
test('freeze and survey preserve lock progress and aim',()=>{const g=harness();stand(g,5);step(g,60);g.activate('freeze');const charge=g.sentries[0].charge,aim=g.sentries[0].aimX;stand(g,7);step(g,120);assert.equal(g.sentries[0].charge,charge);assert.equal(g.sentries[0].aimX,aim);g.effects.freeze=0;g.openMap();step(g,120);assert.equal(g.sentries[0].charge,charge);g.closeMap();step(g,100);assert.equal(g.sentries[0].shots,1);});
test('shutdown clears lock but keeps launched shots; retry clears all runtime state',()=>{const g=harness({sentries:[{...eye,offSwitch:'A'}],switches:[{id:'A',x:25,y:15}]});stand(g,5);step(g,150);assert.equal(g.projectiles.length,1);g.activated.add('A');step(g,1);assert.equal(g.sentries[0].state,'disabled');assert.equal(g.sentries[0].charge,0);assert.equal(g.projectiles.length,1);g.load(g.level);assert.equal(g.projectiles.length,0);assert.equal(g.sentries[0].shots,0);assert.equal(g.sentries[0].charge,0);});
test('sentry shots hit the player and a shield absorbs one shot',()=>{for(const shield of [false,true]){const g=harness({sentries:[{...eye,cooldown:5}]});stand(g,5);if(shield)g.activate('shield');step(g,330);assert.equal(g.sentries[0].shots,1);assert.equal(g.status,shield?'playing':'dying');if(shield)assert.equal(g.effects.shield,0);else assert.equal(g.debris.length,7);}});
test('sentry schema bounds parameters and validates shutdown links and occupied cells',()=>{const g=harness();assert.deepEqual(validateLevel(g.level).sentries,[eye]);for(const patch of [{x:-1},{range:33},{lock:.2},{cooldown:0},{speed:900},{offSwitch:'Z'}])assert.throws(()=>validateLevel({...g.level,sentries:[{...eye,...patch}]}));assert.throws(()=>validateLevel({...g.level,sentries:[eye,eye]}));assert.throws(()=>validateLevel({...g.level,coins:[{x:12,y:8}]}));});
