import test from 'node:test';
import assert from 'node:assert/strict';
import {Game} from '../src/engine.js';
import {emptyLevel,validateLevel} from '../src/levels.js';
const trap={type:'spikes',x:5,y:15,tx:9,ty:15,w:4,delay:1,active:1.5,cooldown:2};
function harness(t=trap){const g=Object.create(Game.prototype);g.keys=new Set();g.render=()=>{};g.cb={hud(){},sound(){},dead(){},win(){}};g.load({...emptyLevel(),version:3,width:32,height:18,traps:[t]});g.start();return g;}
function stand(g,x){Object.assign(g.player,{x:x*30+7,y:454,vx:0,vy:0,ground:true});g.update(1/120);}
function step(g,n){for(let i=0;i<n;i++)g.update(1/120);}
test('pressure plate warns before deploying spikes and resets deterministically',()=>{const g=harness();stand(g,5);assert.equal(g.traps[0].state,'warning');assert.equal(g.traps[0].triggers,1);step(g,100);assert.equal(g.traps[0].state,'warning');step(g,30);assert.equal(g.traps[0].state,'active');step(g,190);assert.equal(g.traps[0].state,'cooldown');step(g,250);assert.equal(g.traps[0].state,'idle');assert.equal(g.traps[0].triggers,1);stand(g,7);stand(g,5);assert.equal(g.traps[0].triggers,2);g.load(g.level);assert.equal(g.traps[0].triggers,0);assert.equal(g.traps[0].state,'idle');});
test('standing still does not repeatedly arm a reset trap',()=>{const g=harness();stand(g,5);step(g,1200);assert.equal(g.traps[0].state,'idle');assert.equal(g.traps[0].triggers,1);});
test('warning spikes are safe; active spikes dismember on contact',()=>{const g=harness();stand(g,5);stand(g,10);assert.equal(g.status,'playing');step(g,130);assert.equal(g.status,'dying');assert.equal(g.debris.length,7);assert.ok(g.blood.length>0);});
test('freeze and survey pause the warning; already active spikes remain lethal',()=>{const g=harness();stand(g,5);g.activate('freeze');const clock=g.clock;step(g,180);assert.equal(g.clock,clock);assert.equal(g.traps[0].state,'warning');g.effects.freeze=0;g.openMap();step(g,180);assert.equal(g.clock,clock);g.closeMap();step(g,130);assert.equal(g.traps[0].state,'active');g.activate('freeze');stand(g,10);assert.equal(g.status,'dying');});
test('shield absorbs one spike hit and grants time to escape',()=>{const g=harness();stand(g,5);step(g,130);g.activate('shield');stand(g,10);assert.equal(g.status,'playing');assert.equal(g.effects.shield,0);assert.ok(g.invulnerable>0);stand(g,14);step(g,200);assert.equal(g.status,'playing');});
test('shutdown cancels warnings and lets the plate rearm after leaving',()=>{const g=harness({...trap,offSwitch:'A'});g.load({...g.level,switches:[{id:'A',x:20,y:15,mode:'toggle'}]});g.start();stand(g,5);g.activated.add('A');step(g,130);assert.equal(g.traps[0].state,'disabled');g.activated.delete('A');step(g,1);assert.equal(g.traps[0].state,'idle');assert.equal(g.traps[0].triggers,1);stand(g,7);stand(g,5);assert.equal(g.traps[0].state,'warning');});
test('dart trap fires once per activation and respects solid cover',()=>{const g=harness({...trap,type:'dart',tx:12,ty:15,dir:'left',speed:250});g.load({...g.level,tiles:[...g.level.tiles,{x:9,y:15,type:'solid'}]});g.start();stand(g,5);step(g,130);assert.equal(g.projectiles.length,1);step(g,120);assert.equal(g.projectiles.length,0);assert.equal(g.status,'playing');step(g,600);assert.equal(g.projectiles.length,0);assert.equal(g.traps[0].triggers,1);});
test('shutdown does not recall a launched dart',()=>{const g=harness({...trap,type:'dart',tx:12,ty:15,dir:'left',speed:120,offSwitch:'A'});g.load({...g.level,switches:[{id:'A',x:20,y:15}]});g.start();stand(g,5);step(g,130);assert.equal(g.projectiles.length,1);g.activated.add('A');step(g,1);assert.equal(g.traps[0].state,'disabled');assert.equal(g.projectiles.length,1);});
test('trap schema preserves links, bounds targets and prevents overlapping objects',()=>{const g=harness();assert.deepEqual(validateLevel(g.level).traps,[trap]);for(const patch of [{delay:.2},{active:0},{cooldown:0},{w:9},{tx:30},{ty:18},{x:-1},{offSwitch:'Z'},{type:'unknown'}])assert.throws(()=>validateLevel({...g.level,traps:[{...trap,...patch}]}));assert.throws(()=>validateLevel({...g.level,traps:[{...trap,tx:5}]}));assert.throws(()=>validateLevel({...g.level,coins:[{x:10,y:15}]}));assert.throws(()=>validateLevel({...g.level,traps:[{...trap,type:'dart',dir:'diagonal',speed:250}]}));});
