import {fail,requireUser,passwordHash,matches} from './auth.mjs';import {transaction,uid} from './store.mjs';import {createHash} from 'node:crypto';import {validateLevel} from '../src/levels.js';import {analyzeLevel} from '../src/level-analysis.js';import {body} from './app.mjs';
const types={level:'levels',set:'level_sets'};
const text=(value,min,max,label)=>{if(typeof value!=='string'||value.trim().length<min||value.length>max||/[\x00-\x08\x0b-\x1f]/.test(value))fail(400,`Invalid ${label}.`);return value.trim();};
export function content(db,kind,id,includeHidden=false){const table=types[kind];if(!table)fail(400,'Unknown content kind.');const row=db.prepare(`SELECT t.*,u.name AS author FROM ${table} t LEFT JOIN users u ON u.id=t.author_id WHERE t.id=? ${includeHidden?'':"AND t.status='published'"}`).get(id);if(!row)fail(404,'Content is unavailable.');return row;}
function summary(db,kind,row,user){const score=db.prepare('SELECT COALESCE(SUM(value),0) AS score,COUNT(*) AS votes FROM votes WHERE kind=? AND item_id=?').get(kind,row.id);const ownVote=db.prepare('SELECT value FROM votes WHERE kind=? AND item_id=? AND user_id=?').get(kind,row.id,user.id)?.value||0;const bookmarked=!!db.prepare('SELECT 1 FROM bookmarks WHERE kind=? AND item_id=? AND user_id=?').get(kind,row.id,user.id);return {id:row.id,kind,name:row.name,description:row.description,author:row.author||'Former member',authorId:row.author_id,created:row.created,parentId:row.parent_id,status:row.status,...score,ownVote,bookmarked,...(kind==='level'?{difficulty:row.difficulty,tags:JSON.parse(row.tags),analysis:JSON.parse(row.analysis),hash:row.content_hash}:{levelIds:JSON.parse(row.level_ids)})};}
export function publishLevel(db,user,input){
 let level,analysis;try{level=validateLevel(input.level);analysis=analyzeLevel(level);}catch(error){fail(400,error.message);}if(analysis.status==='fail')fail(400,analysis.reasons.join(' '));
 const description=text(input.description??'',0,1000,'description'),tags=Array.isArray(input.tags)?[...new Set(input.tags.map(t=>text(t,1,20,'tag')))].slice(0,6):[];if(!['easy','medium','hard','nightmare'].includes(input.difficulty))fail(400,'Choose a difficulty estimate.');
 if(input.parentId){const parent=content(db,'level',input.parentId,true);if(parent.author_id!==user.id)fail(403,'Only the author can create a revision.');}
 if(input.license!=='MIT')fail(400,'Accept the community level license before publishing.');
 const id=uid(),json=JSON.stringify(level);db.prepare('INSERT INTO levels(id,author_id,parent_id,name,description,tags,difficulty,content,content_hash,analysis,created) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(id,user.id,input.parentId||null,level.name,description,JSON.stringify(tags),input.difficulty,json,createHash('sha256').update(json).digest('hex'),JSON.stringify(analysis),Date.now());return summary(db,'level',content(db,'level',id),user);
}
export function publishSet(db,user,input){const name=text(input.name,1,60,'set name'),description=text(input.description??'',0,1000,'description');if(!Array.isArray(input.levelIds)||input.levelIds.length<1||input.levelIds.length>12||new Set(input.levelIds).size!==input.levelIds.length)fail(400,'Choose 1–12 distinct published levels in order.');for(const id of input.levelIds)content(db,'level',id);if(input.parentId&&content(db,'set',input.parentId,true).author_id!==user.id)fail(403,'Only the author can revise a set.');const id=uid();db.prepare('INSERT INTO level_sets(id,author_id,parent_id,name,description,level_ids,created) VALUES(?,?,?,?,?,?,?)').run(id,user.id,input.parentId||null,name,description,JSON.stringify(input.levelIds),Date.now());return summary(db,'set',content(db,'set',id),user);}
export async function communityRoute(ctx){const {db,req,path,user,send,rate}=ctx;if(!path.startsWith('/v1/community')&&!path.startsWith('/v1/account'))return false;requireUser(user);
 if(path==='/v1/account/export'&&req.method==='GET'){send(200,{user,levels:db.prepare('SELECT id,name,description,content,status,created FROM levels WHERE author_id=?').all(user.id),sets:db.prepare('SELECT id,name,description,level_ids,status,created FROM level_sets WHERE author_id=?').all(user.id),generations:db.prepare('SELECT id,model,day,status,spent,tokens,result FROM generation WHERE user_id=?').all(user.id)});return true;}
 if(path==='/v1/account/password'&&req.method==='POST'){const input=await body(req,5000),row=db.prepare('SELECT password FROM users WHERE id=?').get(user.id);rate(`password:${user.id}`,5,900000);if(typeof input.currentPassword!=='string'||input.currentPassword.length>128||!await matches(input.currentPassword,row.password))fail(403,'Current password is incorrect.');if(typeof input.newPassword!=='string'||input.newPassword.length<12||input.newPassword.length>128)fail(400,'Use a 12–128 character password.');const value=await passwordHash(input.newPassword);transaction(db,()=>{db.prepare('UPDATE users SET password=? WHERE id=?').run(value,user.id);db.prepare('DELETE FROM sessions WHERE user_id=?').run(user.id);});send(200,{ok:true,message:'Password changed. Sign in again.'});return true;}
 if(path==='/v1/account/delete'&&req.method==='POST'){const input=await body(req,5000),row=db.prepare('SELECT password FROM users WHERE id=?').get(user.id);if(typeof input.password!=='string'||input.password.length>128||!await matches(input.password,row.password))fail(403,'Password is incorrect.');if(user.role==='admin'&&db.prepare("SELECT COUNT(*) AS n FROM users WHERE role='admin' AND disabled=0").get().n<2)fail(409,'Transfer owner access before deleting the last owner account.');transaction(db,()=>{for(const table of ['levels','level_sets'])db.prepare(`UPDATE ${table} SET status='deleted',author_id=NULL WHERE author_id=?`).run(user.id);db.prepare('DELETE FROM scores WHERE player_id=?').run(user.id);for(const table of ['votes','bookmarks','sessions'])db.prepare(`DELETE FROM ${table} WHERE user_id=?`).run(user.id);db.prepare('UPDATE reports SET user_id=NULL WHERE user_id=?').run(user.id);db.prepare('UPDATE plays SET user_id=NULL WHERE user_id=?').run(user.id);db.prepare('UPDATE generation SET result=NULL,error=NULL WHERE user_id=?').run(user.id);db.prepare('UPDATE users SET name=?,password=?,disabled=1 WHERE id=?').run(`Deleted-${user.id}`,crypto.randomUUID(),user.id);});send(200,{ok:true});return true;}
 if(path==='/v1/community/levels'&&req.method==='POST'){rate(`publish:${user.id}`,20,86400000);send(201,publishLevel(db,user,await body(req,150000)));return true;}
 if(path==='/v1/community/sets'&&req.method==='POST'){rate(`publish:${user.id}`,20,86400000);send(201,publishSet(db,user,await body(req,15000)));return true;}
 if(path==='/v1/community/browse'&&req.method==='GET'){
 const params=new URL(req.url,'http://local').searchParams,kind=params.get('kind')||'level',table=types[kind];if(!table)fail(400,'Unknown content kind.');const q=(params.get('q')||'').slice(0,80),offset=Math.min(10000,Math.max(0,Math.floor(Number(params.get('offset'))||0))),bookmarks=params.get('bookmarks')==='1';
 const rows=db.prepare(`SELECT t.*,u.name AS author FROM ${table} t LEFT JOIN users u ON u.id=t.author_id WHERE t.status='published' AND (t.name LIKE ? ESCAPE '\\' OR t.description LIKE ? ESCAPE '\\') ${bookmarks?'AND EXISTS(SELECT 1 FROM bookmarks b WHERE b.item_id=t.id AND b.kind=? AND b.user_id=?)':''} ORDER BY t.created DESC,t.id LIMIT 24 OFFSET ?`).all(...[...Array(2)].map(()=>`%${q.replace(/[\\%_]/g,'\\$&')}%`),...(bookmarks?[kind,user.id]:[]),offset);
 send(200,{items:rows.map(row=>summary(db,kind,row,user)),offset,next:rows.length===24?offset+24:null});return true;
 }
 const match=/^\/v1\/community\/(level|set)\/([a-zA-Z0-9-]+)(?:\/(vote|bookmark|report|hide|play))?$/.exec(path);
 if(match){const [,kind,id,action]=match,row=content(db,kind,id,action==='hide'&&user.role==='admin');if(req.method==='GET'&&!action){const result=summary(db,kind,row,user);if(kind==='level'){result.level=JSON.parse(row.content);result.plays=db.prepare("SELECT COUNT(*) AS starts,SUM(CASE WHEN outcome='completed' THEN 1 ELSE 0 END) AS completed,SUM(CASE WHEN outcome='abandoned' OR (outcome IS NULL AND created<?) THEN 1 ELSE 0 END) AS abandoned FROM plays WHERE level_id=?").get(Date.now()-3600000,id);}else result.levels=JSON.parse(row.level_ids).map(levelId=>{const l=content(db,'level',levelId);return {...summary(db,'level',l,user),level:JSON.parse(l.content)};});send(200,result);return true;}
 if(req.method==='POST'){
 const input=await body(req,5000);
 if(action==='vote'){if(row.author_id===user.id)fail(400,'You cannot vote on your own content.');if(![-1,0,1].includes(input.value))fail(400,'Vote must be -1, 0 or 1.');rate(`vote:${user.id}`,60);if(input.value===0)db.prepare('DELETE FROM votes WHERE user_id=? AND kind=? AND item_id=?').run(user.id,kind,id);else db.prepare('INSERT INTO votes(user_id,kind,item_id,value) VALUES(?,?,?,?) ON CONFLICT(user_id,kind,item_id) DO UPDATE SET value=excluded.value').run(user.id,kind,id,input.value);send(200,summary(db,kind,row,user));return true;}
 if(action==='bookmark'){if(input.saved)db.prepare('INSERT OR IGNORE INTO bookmarks(user_id,kind,item_id) VALUES(?,?,?)').run(user.id,kind,id);else db.prepare('DELETE FROM bookmarks WHERE user_id=? AND kind=? AND item_id=?').run(user.id,kind,id);send(200,{ok:true});return true;}
 if(action==='report'){rate(`report:${user.id}`,10,86400000);db.prepare('INSERT OR IGNORE INTO reports(id,user_id,kind,item_id,reason,created) VALUES(?,?,?,?,?,?)').run(uid(),user.id,kind,id,text(input.reason,5,500,'report reason'),Date.now());send(200,{ok:true});return true;}
 if(action==='hide'){if(row.author_id!==user.id&&user.role!=='admin')fail(403,'Author or owner access required.');db.prepare(`UPDATE ${types[kind]} SET status=? WHERE id=?`).run(input.restore&&user.role==='admin'?'published':'hidden',id);send(200,{ok:true});return true;}
 if(action==='play'&&kind==='level'){rate(`play:${user.id}`,60);const playId=uid();db.prepare('INSERT INTO plays(id,user_id,level_id,created) VALUES(?,?,?,?)').run(playId,user.id,id,Date.now());send(201,{playId});return true;}
 }
 }
 const play=/^\/v1\/community\/plays\/([a-zA-Z0-9-]+)$/.exec(path);if(play&&req.method==='POST'){const input=await body(req,5000);if(!['completed','abandoned'].includes(input.outcome))fail(400,'Unknown outcome.');const result=db.prepare('UPDATE plays SET outcome=?,finished=? WHERE id=? AND user_id=? AND outcome IS NULL').run(input.outcome,Date.now(),play[1],user.id);if(!result.changes)fail(404,'Open attempt not found.');send(200,{ok:true});return true;}
 if(path==='/v1/community/reports'&&req.method==='GET'){if(user.role!=='admin')fail(403,'Owner access required.');send(200,{reports:db.prepare("SELECT * FROM reports WHERE status='open' ORDER BY created LIMIT 100").all()});return true;}
 const report=/^\/v1\/community\/reports\/([a-zA-Z0-9-]+)$/.exec(path);if(report&&req.method==='POST'){if(user.role!=='admin')fail(403,'Owner access required.');db.prepare("UPDATE reports SET status='reviewed' WHERE id=?").run(report[1]);send(200,{ok:true});return true;}
 return false;
}
