import {body} from './app.mjs';import {content} from './community.mjs';import {fail,requireUser} from './auth.mjs';import {transaction,uid} from './store.mjs';import {RULESET,TICK_RATE} from '../src/replay.js';import {competitionLevel,verifyReplay} from './verify.mjs';
export function competition(db,id){const row=db.prepare('SELECT * FROM competitions WHERE id=?').get(id);if(!row)fail(404,'Competition not found.');return {...row,snapshot:JSON.parse(row.snapshot),rules:JSON.parse(row.rules)};}
export function createCompetition(db,user,input,now=Date.now()){
 if(typeof input.name!=='string'||!input.name.trim()||input.name.length>60||!['easy','medium','hard','nightmare'].includes(input.difficulty)||!['itemFree','assisted'].includes(input.assistance))fail(400,'Choose a name, difficulty and helper policy.');
 if(![input.opens,input.closes,input.duration].every(Number.isSafeInteger)||input.opens<now-60000||input.opens>now+30*86400000||input.closes<=input.opens||input.closes-input.opens>30*86400000||input.duration<60||input.duration>3600||input.closes-input.opens<input.duration*1000)fail(400,'Use a future window up to 30 days and a 1–60 minute attempt duration.');
 const set=content(db,'set',input.setId),snapshot=JSON.parse(set.level_ids).map(id=>{const row=content(db,'level',id);return {id,name:row.name,hash:row.content_hash,author:row.author||'Former member',level:competitionLevel(JSON.parse(row.content))};});
 const id=uid(),rules={ruleset:RULESET,difficulty:input.difficulty,assistance:input.assistance,seed:parseInt(id.replaceAll('-','').slice(0,8),16),pause:'wall-clock-continues',retry:'wall-clock-continues',helpers:'one of each per level',ranking:'server elapsed including pauses/retries/network; replay required'};
 db.prepare('INSERT INTO competitions(id,author_id,set_id,name,snapshot,rules,opens,closes,duration,created) VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,user.id,input.setId,input.name.trim(),JSON.stringify(snapshot),JSON.stringify(rules),input.opens,input.closes,input.duration,now);return competition(db,id);
}
export function startAttempt(db,user,event,now=Date.now()){
 if(now<event.opens||now>=event.closes)fail(409,'This competition is outside its entry window.');
 const old=db.prepare("SELECT * FROM attempts WHERE user_id=? AND competition_id=? AND status='active' AND deadline>?").get(user.id,event.id,now);if(old)return old;
 const id=uid();db.prepare('INSERT INTO attempts(id,user_id,competition_id,started,deadline) VALUES(?,?,?,?,?)').run(id,user.id,event.id,now,Math.min(event.closes,now+event.duration*1000));return db.prepare('SELECT * FROM attempts WHERE id=?').get(id);
}
export async function submitRun(db,user,attemptId,input,now=Date.now(),verifier=verifyReplay){
 const attempt=transaction(db,()=>{
 const row=db.prepare('SELECT * FROM attempts WHERE id=? AND user_id=?').get(attemptId,user.id);if(!row)fail(404,'Attempt not found.');
 if(!Number.isSafeInteger(input.position)||input.position<0)fail(400,'Invalid level position.');const previous=db.prepare('SELECT position FROM attempt_runs WHERE attempt_id=? AND position=?').get(attemptId,input.position);if(previous)return {...row,duplicate:true};
 if(row.status!=='active'||now>row.deadline)fail(409,'Attempt has ended.');if(input.position!==row.progress)fail(409,'Submit the next level in order.');if(row.checking)fail(429,'A replay is already being checked.');db.prepare('UPDATE attempts SET checking=1 WHERE id=?').run(row.id);return row;});
 if(attempt.duplicate)return {attempt,accepted:true,duplicate:true};
 try{const event=competition(db,attempt.competition_id);if(event.rules.ruleset!==RULESET)fail(409,'This competition uses an unavailable rules version.');const expected=event.snapshot[input.position];if(input.levelHash!==expected.hash)fail(409,'Level revision does not match the competition.');const result=await verifier({level:expected.level,replay:input.replay,...event.rules});if(!result.ok)fail(400,result.error);
 const prior=db.prepare('SELECT COALESCE(SUM(ticks),0) AS n FROM attempt_runs WHERE attempt_id=?').get(attemptId).n;
 if(now-attempt.started+100<(prior+result.ticks)/TICK_RATE*1000)fail(400,'The replay is faster than the server attempt clock.');
 return transaction(db,()=>{const current=db.prepare('SELECT * FROM attempts WHERE id=?').get(attemptId);if(current.status!=='active'||current.progress!==input.position)fail(409,'Attempt state changed.');db.prepare('INSERT INTO attempt_runs(attempt_id,position,level_hash,replay,ticks,submitted) VALUES(?,?,?,?,?,?)').run(attemptId,input.position,expected.hash,JSON.stringify(input.replay),result.ticks,now);const done=input.position+1===event.snapshot.length;db.prepare('UPDATE attempts SET progress=progress+1,checking=0,status=?,finished=?,total_ms=? WHERE id=?').run(done?'completed':'active',done?now:null,done?now-attempt.started:null,attemptId);return {accepted:true,verified:result,attempt:db.prepare('SELECT * FROM attempts WHERE id=?').get(attemptId)};});
 }finally{db.prepare('UPDATE attempts SET checking=0 WHERE id=?').run(attemptId);}
}
export async function competitionRoute(ctx){const {db,req,path,user,send,rate}=ctx;if(!path.startsWith('/v1/competitions')&&!path.startsWith('/v1/attempts'))return false;requireUser(user);
 if(path==='/v1/competitions'&&req.method==='POST'){rate(`competition:${user.id}`,10,86400000);send(201,createCompetition(db,user,await body(req,5000)));return true;}
 if(path==='/v1/competitions'&&req.method==='GET'){send(200,{events:db.prepare('SELECT id,name,opens,closes,duration,rules FROM competitions WHERE id NOT IN(SELECT event_id FROM lobbies) ORDER BY created DESC LIMIT 50').all().map(e=>({...e,rules:JSON.parse(e.rules)}))});return true;}
 const eventMatch=/^\/v1\/competitions\/([a-zA-Z0-9-]+)(?:\/(start|standings))?$/.exec(path);
 if(eventMatch){const event=competition(db,eventMatch[1]);if(req.method==='GET'&&!eventMatch[2]){send(200,event);return true;}if(req.method==='POST'&&eventMatch[2]==='start'){rate(`attempt:${user.id}`,60,3600000);const room=db.prepare('SELECT id,state FROM lobbies WHERE event_id=?').get(event.id);if(room){const member=db.prepare('SELECT attempt_id,forfeit FROM lobby_members WHERE lobby_id=? AND user_id=?').get(room.id,user.id);if(!member?.attempt_id||member.forfeit||room.state!=='running')fail(409,'Enter through your active lobby.');send(200,{lobbyId:room.id,event,attempt:db.prepare('SELECT * FROM attempts WHERE id=?').get(member.attempt_id)});return true;}send(201,{event,attempt:startAttempt(db,user,event)});return true;}if(req.method==='GET'&&eventMatch[2]==='standings'){const rows=db.prepare("SELECT a.id,a.user_id,u.name,a.total_ms,a.finished FROM attempts a JOIN users u ON a.user_id=u.id WHERE a.competition_id=? AND a.status='completed' AND u.disabled=0 ORDER BY a.total_ms,a.finished LIMIT 500").all(event.id),seen=new Set(),results=[];for(const row of rows)if(!seen.has(row.user_id)){seen.add(row.user_id);results.push({attemptId:row.id,name:row.name,totalMs:row.total_ms});if(results.length===100)break;}send(200,{rules:event.rules,results});return true;}}
 const attemptMatch=/^\/v1\/attempts\/([a-zA-Z0-9-]+)(?:\/(submit|abandon|replays))?$/.exec(path);
 if(attemptMatch){const attempt=db.prepare('SELECT * FROM attempts WHERE id=? AND user_id=?').get(attemptMatch[1],user.id);if(!attempt)fail(404,'Attempt not found.');if(req.method==='GET'&&!attemptMatch[2]){send(200,{attempt,event:competition(db,attempt.competition_id),serverTime:Date.now()});return true;}if(req.method==='POST'&&attemptMatch[2]==='submit'){rate(`verify:${user.id}`,30,60000);send(200,await submitRun(db,user,attempt.id,await body(req,800000)));return true;}if(req.method==='POST'&&attemptMatch[2]==='abandon'){db.prepare("UPDATE attempts SET status='abandoned',checking=0 WHERE id=? AND status='active'").run(attempt.id);send(200,{ok:true});return true;}if(req.method==='GET'&&attemptMatch[2]==='replays'){send(200,{rules:competition(db,attempt.competition_id).rules,replays:db.prepare('SELECT position,level_hash,ticks,replay FROM attempt_runs WHERE attempt_id=? ORDER BY position').all(attempt.id).map(r=>({...r,replay:JSON.parse(r.replay)}))});return true;}}
 return false;
}
