import {body} from './app.mjs';import {uid,transaction} from './store.mjs';import {fail,requireUser} from './auth.mjs';import {competition,startAttempt} from './competitions.mjs';import {content} from './community.mjs';
export function advanceLobby(db,id,now=Date.now()){
 return transaction(db,()=>{let room=db.prepare('SELECT * FROM lobbies WHERE id=?').get(id);if(!room)fail(404,'Lobby not found.');
 if(room.state==='waiting'){
 db.prepare('DELETE FROM lobby_members WHERE lobby_id=? AND last_seen<?').run(id,now-60000);
 const first=db.prepare('SELECT user_id FROM lobby_members WHERE lobby_id=? ORDER BY joined,user_id LIMIT 1').get(id);if(!first||now-room.created>1800000)db.prepare("UPDATE lobbies SET state='closed' WHERE id=?").run(id);else if(!db.prepare('SELECT 1 FROM lobby_members WHERE lobby_id=? AND user_id=?').get(id,room.host_id))db.prepare('UPDATE lobbies SET host_id=? WHERE id=?').run(first.user_id,id);
 }
 room=db.prepare('SELECT * FROM lobbies WHERE id=?').get(id);
 if(room.state==='countdown'&&now>=room.countdown){const event=competition(db,room.event_id);for(const member of db.prepare('SELECT user_id FROM lobby_members WHERE lobby_id=?').all(id)){const attempt=startAttempt(db,{id:member.user_id},event,room.countdown);db.prepare('UPDATE lobby_members SET attempt_id=? WHERE lobby_id=? AND user_id=?').run(attempt.id,id,member.user_id);}db.prepare("UPDATE lobbies SET state='running' WHERE id=?").run(id);}
 room=db.prepare('SELECT * FROM lobbies WHERE id=?').get(id);
 if(room.state==='running'){db.prepare("UPDATE attempts SET status='expired',checking=0 WHERE competition_id=? AND status='active' AND deadline<?").run(room.event_id,now);const active=db.prepare("SELECT COUNT(*) n FROM lobby_members m JOIN attempts a ON a.id=m.attempt_id WHERE m.lobby_id=? AND m.forfeit=0 AND a.status='active'").get(id).n;if(!active)db.prepare("UPDATE lobbies SET state='finished' WHERE id=?").run(id);}
 return db.prepare('SELECT * FROM lobbies WHERE id=?').get(id);});
}
export function lobbyView(db,id,user,now=Date.now()){
 const room=advanceLobby(db,id,now),members=db.prepare('SELECT m.*,u.name,a.progress,a.status AS attempt_status,a.total_ms FROM lobby_members m JOIN users u ON u.id=m.user_id LEFT JOIN attempts a ON a.id=m.attempt_id WHERE m.lobby_id=? ORDER BY m.joined,m.user_id').all(id).map(m=>({id:m.user_id,name:m.name,ready:!!m.ready,online:now-m.last_seen<10000,progress:m.progress||0,status:m.forfeit?'forfeit':m.attempt_status||'waiting',totalMs:m.total_ms}));const own=db.prepare('SELECT * FROM lobby_members WHERE lobby_id=? AND user_id=?').get(id,user.id);return {...room,members,serverTime:now,me:own?{ready:!!own.ready,forfeit:!!own.forfeit,attemptId:own.attempt_id}:null,...(own?.attempt_id&&!own.forfeit?{race:{lobbyId:id,event:competition(db,room.event_id),attempt:db.prepare('SELECT * FROM attempts WHERE id=?').get(own.attempt_id)}}:{})};
}
export function createLobby(db,user,input,now=Date.now()){
 for(const old of db.prepare("SELECT id FROM lobbies WHERE host_id=? AND state IN('waiting','countdown','running')").all(user.id))advanceLobby(db,old.id,now);
 const source=competition(db,input.competitionId);for(const room of source.snapshot)content(db,'level',room.id);if(typeof input.name!=='string'||!input.name.trim()||input.name.length>60)fail(400,'Choose a lobby name (1–60 characters).');if(db.prepare("SELECT COUNT(*) n FROM lobbies WHERE host_id=? AND state IN('waiting','countdown','running')").get(user.id).n>=3)fail(429,'Close one of your existing rooms first.');
 const id=uid(),eventId=uid();transaction(db,()=>{db.prepare('INSERT INTO competitions(id,author_id,set_id,name,snapshot,rules,opens,closes,duration,created) VALUES(?,?,?,?,?,?,?,?,?,?)').run(eventId,user.id,source.set_id,input.name.trim(),JSON.stringify(source.snapshot),JSON.stringify(source.rules),now+86400000,now+86400000+source.duration*1000,source.duration,now);db.prepare('INSERT INTO lobbies(id,host_id,event_id,name,created) VALUES(?,?,?,?,?)').run(id,user.id,eventId,input.name.trim(),now);db.prepare('INSERT INTO lobby_members(lobby_id,user_id,joined,last_seen) VALUES(?,?,?,?)').run(id,user.id,now,now);});return lobbyView(db,id,user,now);
}
export function joinLobby(db,user,id,now=Date.now()){
 advanceLobby(db,id,now);transaction(db,()=>{const room=db.prepare('SELECT * FROM lobbies WHERE id=?').get(id),own=db.prepare('SELECT * FROM lobby_members WHERE lobby_id=? AND user_id=?').get(id,user.id);if(own){if(own.forfeit)fail(409,'You forfeited this race.');db.prepare('UPDATE lobby_members SET last_seen=? WHERE lobby_id=? AND user_id=?').run(now,id,user.id);return;}if(room.state!=='waiting')fail(409,'This lobby no longer accepts entrants.');if(db.prepare('SELECT COUNT(*) n FROM lobby_members WHERE lobby_id=?').get(id).n>=8)fail(409,'This lobby is full (8 players).');db.prepare('INSERT INTO lobby_members(lobby_id,user_id,joined,last_seen) VALUES(?,?,?,?)').run(id,user.id,now,now);});return lobbyView(db,id,user,now);
}
export function startLobby(db,user,id,now=Date.now()){
 advanceLobby(db,id,now);transaction(db,()=>{const room=db.prepare('SELECT * FROM lobbies WHERE id=?').get(id);if(room.host_id!==user.id)fail(403,'Only the current host can start.');if(room.state!=='waiting')fail(409,'The lobby is no longer waiting.');const members=db.prepare('SELECT * FROM lobby_members WHERE lobby_id=?').all(id);if(members.length<2||members.some(m=>!m.ready||now-m.last_seen>10000))fail(409,'At least two connected players must all be ready.');const event=competition(db,room.event_id),at=now+5000;db.prepare("UPDATE lobbies SET state='countdown',countdown=? WHERE id=?").run(at,id);db.prepare('UPDATE competitions SET opens=?,closes=? WHERE id=?').run(at,at+event.duration*1000,event.id);});return lobbyView(db,id,user,now);
}
export function leaveLobby(db,user,id,now=Date.now()){
 const room=advanceLobby(db,id,now);transaction(db,()=>{const own=db.prepare('SELECT * FROM lobby_members WHERE lobby_id=? AND user_id=?').get(id,user.id);if(!own)return;
 if(['waiting','countdown'].includes(room.state)){db.prepare('DELETE FROM lobby_members WHERE lobby_id=? AND user_id=?').run(id,user.id);if(room.state==='countdown'){db.prepare("UPDATE lobbies SET state='waiting',countdown=NULL WHERE id=?").run(id);db.prepare('UPDATE lobby_members SET ready=0 WHERE lobby_id=?').run(id);}}
 else{db.prepare('UPDATE lobby_members SET forfeit=1 WHERE lobby_id=? AND user_id=?').run(id,user.id);db.prepare("UPDATE attempts SET status='abandoned',checking=0 WHERE id=? AND status='active'").run(own.attempt_id);}
 if(room.host_id===user.id){const next=db.prepare('SELECT user_id FROM lobby_members WHERE lobby_id=? AND forfeit=0 ORDER BY joined,user_id LIMIT 1').get(id);if(next)db.prepare('UPDATE lobbies SET host_id=? WHERE id=?').run(next.user_id,id);else db.prepare("UPDATE lobbies SET state='closed' WHERE id=?").run(id);}});return lobbyView(db,id,user,now);
}
export async function lobbyRoute(ctx){const {db,req,path,user,send,rate}=ctx;if(!path.startsWith('/v1/lobbies'))return false;requireUser(user);
 if(path==='/v1/lobbies'&&req.method==='GET'){send(200,{lobbies:db.prepare("SELECT id,name,state,host_id,created FROM lobbies WHERE state IN('waiting','countdown','running') AND created>? ORDER BY created DESC LIMIT 50").all(Date.now()-3600000)});return true;}
 if(path==='/v1/lobbies'&&req.method==='POST'){rate(`lobby-create:${user.id}`,10,86400000);send(201,createLobby(db,user,await body(req,5000)));return true;}
 const match=/^\/v1\/lobbies\/([a-zA-Z0-9-]+)(?:\/(join|ready|start|leave|close))?$/.exec(path);if(!match)return false;const [,id,action]=match;
 if(req.method==='GET'&&!action){rate(`lobby-poll:${user.id}`,60);db.prepare('UPDATE lobby_members SET last_seen=? WHERE lobby_id=? AND user_id=? AND forfeit=0').run(Date.now(),id,user.id);send(200,lobbyView(db,id,user));return true;}
 if(req.method==='POST'){const input=await body(req,5000);if(action==='join'){send(200,joinLobby(db,user,id));return true;}if(action==='start'){send(200,startLobby(db,user,id));return true;}if(action==='leave'){send(200,leaveLobby(db,user,id));return true;}if(action==='ready'){const room=advanceLobby(db,id);if(room.state!=='waiting'||typeof input.ready!=='boolean')fail(409,'Readiness can change only while waiting.');const changed=db.prepare('UPDATE lobby_members SET ready=?,last_seen=? WHERE lobby_id=? AND user_id=?').run(input.ready?1:0,Date.now(),id,user.id);if(!changed.changes)fail(403,'Join the lobby first.');send(200,lobbyView(db,id,user));return true;}if(action==='close'){const room=advanceLobby(db,id);if(room.host_id!==user.id&&user.role!=='admin')fail(403,'Host or owner access required.');transaction(db,()=>{db.prepare("UPDATE lobbies SET state='closed' WHERE id=?").run(id);db.prepare("UPDATE attempts SET status='abandoned',checking=0 WHERE competition_id=? AND status='active'").run(room.event_id);});send(200,{ok:true});return true;}}
 return false;
}
