import {body} from './app.mjs';import {uid} from './store.mjs';import {fail,hash,token,requireUser} from './auth.mjs';import {campaignLevel,campaignRevision} from '../src/levels.js';import {bossArena,hasBoss} from '../src/bosses.js';import {RULESET,validateTape,TICK_RATE} from '../src/replay.js';import {verifyReplay} from './verify.mjs';
export async function scoreRoute(ctx){const {db,req,path,user,send,rate,ip}=ctx;if(!path.startsWith('/v1/scores'))return false;const kidsOrigin=req.headers.origin==='https://kids-bnb.minizap.online';
 if(path==='/v1/scores/guest'&&req.method==='POST'){rate(`guest:${ip}`,10,86400000);const id=uid(),secret=token(),n=parseInt(id.replaceAll('-','').slice(0,8),16),label=['Clover','Cloud','Rainbow','Sunny'][n%4]+['Fox','Owl','Otter','Panda'][Math.floor(n/4)%4]+String(n%1000).padStart(3,'0');db.prepare('INSERT INTO score_guests(id,token_hash,label,expires) VALUES(?,?,?,?)').run(id,hash(secret),label,Date.now()+90*86400000);send(201,{token:secret,label});return true;}
 if(path==='/v1/scores'&&req.method==='GET'){const q=new URL(req.url,'http://local').searchParams,edition=kidsOrigin?'kids':q.get('edition')||'original',stage=Number(q.get('stage')),difficulty=q.get('difficulty')||'medium',assistance=q.get('assistance')||'itemFree';if(!['kids','original'].includes(edition)||!Number.isInteger(stage)||stage<0||stage>98||!['easy','medium','hard','nightmare'].includes(difficulty)||!['itemFree','assisted'].includes(assistance))fail(400,'Invalid leaderboard category.');const results=db.prepare('SELECT id,label,ticks,created FROM scores WHERE edition=? AND stage=? AND revision=? AND ruleset=? AND difficulty=? AND assistance=? ORDER BY ticks,created LIMIT 100').all(edition,stage,campaignRevision(stage),RULESET,difficulty,assistance).map(r=>({id:r.id,name:r.label,time:r.ticks/TICK_RATE}));send(200,{edition,stage,revision:campaignRevision(stage),ruleset:RULESET,difficulty,assistance,results});return true;}
 const replayMatch=/^\/v1\/scores\/([a-zA-Z0-9-]+)\/replay$/.exec(path);if(replayMatch&&req.method==='GET'){const row=db.prepare('SELECT stage,revision,ruleset,edition,difficulty,assistance,replays FROM scores WHERE id=?').get(replayMatch[1]);if(!row||kidsOrigin&&row.edition!=='kids')fail(404,'Replay not found.');if(row.revision!==campaignRevision(row.stage)||row.ruleset!==RULESET)fail(409,'This replay needs an older game revision.');send(200,{...row,replays:JSON.parse(row.replays)});return true;}
 if(path==='/v1/scores'&&req.method==='POST'){
 rate(`score:${ip}`,30,60000);const input=await body(req,1600000),edition=kidsOrigin?'kids':input.edition;if(!['kids','original'].includes(edition))fail(400,'Invalid edition.');let player;
 if(edition==='kids'){if(typeof input.guestToken!=='string'||input.guestToken.length>100)fail(401,'Create a highscore nickname first.');player=db.prepare('SELECT id,label FROM score_guests WHERE token_hash=? AND expires>?').get(hash(input.guestToken),Date.now());if(!player)fail(401,'Highscore nickname expired. Create a new one.');}
 else{requireUser(user);player={id:user.id,label:user.name};}
 const stage=input.stage,difficulty=input.difficulty;if(!Number.isInteger(stage)||stage<0||stage>98||!['easy','medium','hard','nightmare'].includes(difficulty)||input.revision!==campaignRevision(stage)||!Array.isArray(input.replays)||input.replays.length!==(hasBoss(stage)?2:1))fail(400,'The campaign stage, revision or replay count is invalid.');
 let helpers=0;try{for(const tape of input.replays)helpers+=Object.values(validateTape(tape).uses).reduce((a,b)=>a+b,0);}catch(error){fail(400,error.message);}const assistance=helpers?'assisted':'itemFree';let ticks=0,effects={};
 for(let i=0;i<input.replays.length;i++){const result=await verifyReplay({level:i?bossArena(stage):campaignLevel(stage),difficulty,seed:stage+1,replay:input.replays[i],assistance,maxHelperUses:100,initialEffects:effects});if(!result.ok)fail(400,result.error);ticks+=result.ticks;effects=result.effects;}
 const id=uid();db.prepare('INSERT INTO scores(id,player_id,label,edition,stage,revision,ruleset,difficulty,assistance,ticks,replays,created) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(player_id,edition,stage,revision,ruleset,difficulty,assistance) DO UPDATE SET label=excluded.label,ticks=excluded.ticks,replays=excluded.replays,created=excluded.created WHERE excluded.ticks<scores.ticks').run(id,player.id,player.label,edition,stage,input.revision,RULESET,difficulty,assistance,ticks,JSON.stringify(input.replays),Date.now());send(201,{verified:true,name:player.label,time:ticks/TICK_RATE,assistance});return true;
 }
 return false;
}
