import {lobbyUI} from './lobby-ui.js';
import {competitionUI} from './competition-ui.js';
import {validateLevel} from './levels.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const saveFile=(value,name)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
export async function communityUI({root,user,api,getDraft,onPlay,onDraft,close,ai,startRace,currentAttempt,stopRace}){
 let selection=[];try{selection=JSON.parse(localStorage.getItem(`bnb-set-draft:${user.id}`)||'[]');if(!Array.isArray(selection))selection=[];}catch{}selection=selection.slice(0,12);
 const persist=()=>{try{localStorage.setItem(`bnb-set-draft:${user.id}`,JSON.stringify(selection));}catch{}};
 const status=message=>{const el=root.querySelector('[role=status]');if(el)el.textContent=message;};
 const safe=fn=>async e=>{try{await fn(e);}catch(error){status(error.message);}};
 function frame(title){root.innerHTML=`<h2>${esc(title)}</h2><nav class="community-tabs"><button class="secondary" data-tab="browse">Browse</button><button class="secondary" data-tab="publish">Publish editor draft</button><button class="secondary" data-tab="set">Set builder (${selection.length})</button><button class="secondary" data-tab="ai">AI workshop</button><button class="secondary" data-tab="lobbies">Live lobbies</button><button class="secondary" data-tab="competitions">Competitions</button><button class="secondary" data-tab="account">Account</button>${user.role==='admin'?'<button class="secondary" data-tab="moderation">Reports</button>':''}</nav><p role="status"></p><div id="community-body"></div>`;for(const button of root.querySelectorAll('[data-tab]'))button.onclick=safe(()=>({browse:()=>browse(),publish:()=>publish(),set:()=>setBuilder(),ai,lobbies:()=>lobbyUI({root:frame('Live lobbies'),user,api,startRace,close,currentAttempt,stopRace}),competitions:()=>competitionUI({root:frame('Competitions'),api,startRace,close}),account,moderation}[button.dataset.tab])());return root.querySelector('#community-body');}
 async function browse(query='',kind='level',bookmarked=false,offset=0){const box=frame('Community workshop');box.innerHTML=`<p>Invite-only community. Layout checks do not prove a level is solvable. Votes are opinions, not verification.</p><form id="community-search"><input name="q" maxlength="80" value="${esc(query)}" aria-label="Search levels and sets" placeholder="Search names or descriptions"><select name="kind"><option value="level" ${kind==='level'?'selected':''}>Levels</option><option value="set" ${kind==='set'?'selected':''}>Level sets</option></select><label><span><input name="bookmarks" type="checkbox" ${bookmarked?'checked':''}> Bookmarks only</span></label><button class="secondary">Search</button></form><div class="community-list"></div>`;
 box.querySelector('form').onsubmit=safe(e=>{e.preventDefault();const input=Object.fromEntries(new FormData(e.currentTarget));return browse(input.q,input.kind,!!input.bookmarks);});
 const result=await api(`/v1/community/browse?kind=${kind}&q=${encodeURIComponent(query)}&bookmarks=${bookmarked?1:0}&offset=${offset}`);const list=box.querySelector('.community-list');list.innerHTML=result.items.length?result.items.map(item=>`<article><h3>${esc(item.name)}</h3><p>${esc(item.description)}</p><small>By ${esc(item.author)} · ${item.score} votes · ${kind==='level'?esc(item.difficulty)+' · route unverified':item.levelIds.length+' levels'}</small><button class="secondary" data-open="${item.id}">Open ${kind}</button></article>`).join(''):'<p>No matching publications yet.</p>';
 for(const button of list.querySelectorAll('[data-open]'))button.onclick=safe(()=>detail(kind,button.dataset.open));if(result.next!==null){const next=document.createElement('button');next.textContent='More results';next.className='secondary';next.onclick=safe(()=>browse(query,kind,bookmarked,result.next));list.append(next);}
 }
 async function detail(kind,id){const item=await api(`/v1/community/${kind}/${id}`),box=frame(item.name),url=`${location.origin}/?community=${kind}:${id}`;
 box.innerHTML=`<p>${esc(item.description)}</p><p>By ${esc(item.author)} · immutable revision ${esc(id)} · ${item.score} votes</p><label>Share link<input readonly value="${esc(url)}"></label><div class="community-actions"><button class="primary" id="community-play">${kind==='set'?'Play set':'Play level'}</button><button class="secondary" id="community-export">Download JSON</button><button class="secondary" id="community-bookmark">${item.bookmarked?'Remove bookmark':'Bookmark'}</button><button class="secondary" data-vote="1" ${item.authorId===user.id?'disabled':''}>▲ ${item.ownVote===1?'Voted':''}</button><button class="secondary" data-vote="-1" ${item.authorId===user.id?'disabled':''}>▼ ${item.ownVote===-1?'Voted':''}</button>${item.authorId===user.id||user.role==='admin'?'<button class="secondary" id="community-hide">Unpublish</button>':''}</div>${kind==='level'?`<p>Route ${esc(item.analysis.status)}. ${esc(item.analysis.reasons.join(' '))}</p><p>${item.plays.starts} launches · ${item.plays.completed||0} self-reported completions · ${item.plays.abandoned||0} abandoned/expired. These are not ranked scores.</p><button class="secondary" id="community-add">Add to my set</button><button class="secondary" id="community-edit">Edit a local copy</button>`:`<button class="secondary" id="create-set-event">Create competition</button><ol>${item.levels.map(l=>`<li>${esc(l.name)} — ${esc(l.author)}</li>`).join('')}</ol>`}<details><summary>Report content</summary><form id="community-report"><textarea name="reason" required minlength="5" maxlength="500" placeholder="Describe the issue"></textarea><button class="secondary">Send report to owner</button></form></details>`;
 box.querySelector('#community-play').onclick=safe(async()=>{const levels=kind==='level'?[item]:item.levels;close();await onPlay(levels.map(l=>({id:l.id,level:validateLevel(l.level)})),item);});
 box.querySelector('#community-export').onclick=()=>saveFile(kind==='level'?{...item.level,attribution:{author:item.author,revision:id,license:'MIT'}}:{schemaVersion:1,name:item.name,revision:id,levels:item.levels.map(l=>({level:l.level,author:l.author,revision:l.id,license:'MIT'}))},kind==='level'?'community-level.n-level.json':'community-set.json');
 box.querySelector('#community-bookmark').onclick=safe(async()=>{await api(`/v1/community/${kind}/${id}/bookmark`,{method:'POST',data:{saved:!item.bookmarked}});await detail(kind,id);});
 for(const button of box.querySelectorAll('[data-vote]'))button.onclick=safe(async()=>{const vote=Number(button.dataset.vote);await api(`/v1/community/${kind}/${id}/vote`,{method:'POST',data:{value:item.ownVote===vote?0:vote}});await detail(kind,id);});
 if(kind==='set')box.querySelector('#create-set-event').onclick=safe(()=>competitionUI({root:frame('Competition'),api,startRace,close,setId:id}));
 const hide=box.querySelector('#community-hide');if(hide)hide.onclick=safe(async()=>{await api(`/v1/community/${kind}/${id}/hide`,{method:'POST',data:{}});await browse();});
 if(kind==='level'){box.querySelector('#community-add').onclick=()=>{if(selection.length>=12)return status('A set holds up to 12 levels.');if(!selection.some(x=>x.id===id))selection.push({id,name:item.name});persist();status(`Added ${item.name}. Open Set builder to order and publish.`);};box.querySelector('#community-edit').onclick=()=>{onDraft(validateLevel(item.level));close();};}
 box.querySelector('#community-report').onsubmit=safe(async e=>{e.preventDefault();await api(`/v1/community/${kind}/${id}/report`,{method:'POST',data:Object.fromEntries(new FormData(e.currentTarget))});status('Report sent to the owner.');});
 }
 function publish(){const level=validateLevel(getDraft()),box=frame('Publish the current editor draft');box.innerHTML=`<h3>${esc(level.name)}</h3><p>Publishing creates an immutable revision. Your name, description and level become visible to invited members. Test the route first; automated checks do not prove playability.</p><form id="publish-level"><label>Description<textarea name="description" maxlength="1000" rows="3"></textarea></label><label>Difficulty estimate<select name="difficulty"><option>easy</option><option selected>medium</option><option>hard</option><option>nightmare</option></select></label><label>Tags (comma separated)<input name="tags" maxlength="120"></label><label>Previous revision ID (optional; must be yours)<input name="parentId" maxlength="40"></label><label><span><input type="checkbox" required name="license"> I created this level or have permission to share it under the MIT license, with attribution.</span></label><button class="primary">Publish revision</button></form>`;box.querySelector('form').onsubmit=safe(async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));const result=await api('/v1/community/levels',{method:'POST',data:{...data,level,tags:data.tags.split(',').map(x=>x.trim()).filter(Boolean),license:'MIT',parentId:data.parentId||undefined}});await detail('level',result.id);});}
 function setBuilder(){const box=frame('Create a level set');box.innerHTML=`<p>Choose up to 12 immutable revisions from Browse → Open level → Add to my set. Publishing freezes this order; a later revision gets a new share link.</p><ol>${selection.map((l,i)=>`<li>${esc(l.name)} <button class="secondary" data-move="${i}" ${i===0?'disabled':''}>Move up</button><button class="secondary" data-remove="${i}">Remove</button></li>`).join('')}</ol><form><label>Set name<input name="name" required maxlength="60"></label><label>Description<textarea name="description" maxlength="1000"></textarea></label><label>Previous set revision ID (optional)<input name="parentId" maxlength="40"></label><button class="primary" ${selection.length?'':'disabled'}>Publish ordered set</button></form><button class="secondary" id="set-export">Export set draft</button>`;for(const b of box.querySelectorAll('[data-remove]'))b.onclick=()=>{selection.splice(+b.dataset.remove,1);persist();setBuilder();};for(const b of box.querySelectorAll('[data-move]'))b.onclick=()=>{const i=+b.dataset.move;[selection[i-1],selection[i]]=[selection[i],selection[i-1]];persist();setBuilder();};box.querySelector('#set-export').onclick=()=>saveFile({schemaVersion:1,levelReferences:selection},'set-draft.json');box.querySelector('form').onsubmit=safe(async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));const result=await api('/v1/community/sets',{method:'POST',data:{...data,parentId:data.parentId||undefined,levelIds:selection.map(l=>l.id)}});await detail('set',result.id);});}
 function account(){const box=frame('Your community account');box.innerHTML=`<p>Signed in as ${esc(user.name)}. Offline career saves stay in your browser. Account export includes your publications and generation results.</p><button class="secondary" id="account-export">Export account data</button>${user.role==='admin'?'<button class="secondary" id="account-invite">Create one-use invitation</button><output id="invite-output"></output>':''}<details><summary>Change password</summary><form id="account-password"><label>Current password<input type="password" name="currentPassword" required maxlength="128"></label><label>New password<input type="password" name="newPassword" required minlength="12" maxlength="128"></label><button class="secondary">Change password and sign out</button></form></details><details><summary>Delete account</summary><p>This disables sign-in, removes votes/bookmarks, and hides your publications. Anonymous revision data and usage records may remain for integrity and abuse prevention. Local game saves are unaffected.</p><form id="account-delete"><label>Password<input type="password" name="password" required maxlength="128"></label><label><span><input type="checkbox" required> I want to delete this account and hide its publications.</span></label><button class="secondary">Delete account</button></form></details>`;
 box.querySelector('#account-export').onclick=safe(async()=>saveFile(await api('/v1/account/export'),'bnb-account.json'));const invite=box.querySelector('#account-invite');if(invite)invite.onclick=safe(async()=>{const result=await api('/v1/invites',{method:'POST',data:{}});box.querySelector('#invite-output').textContent=`One use, expires in 7 days: ${result.invite}`;});for(const action of ['password','delete'])box.querySelector(`#account-${action}`).onsubmit=safe(async e=>{e.preventDefault();await api(`/v1/account/${action}`,{method:'POST',data:Object.fromEntries(new FormData(e.currentTarget))});close();});
 }
 async function moderation(){const box=frame('Owner moderation queue'),result=await api('/v1/community/reports');box.innerHTML=result.reports.map(r=>`<article><h3>${esc(r.kind)} ${esc(r.item_id)}</h3><p>${esc(r.reason)}</p><button class="secondary" data-inspect="${r.id}">Inspect</button><button class="secondary" data-hide="${r.id}">Hide content</button><button class="secondary" data-resolve="${r.id}">Mark reviewed</button></article>`).join('')||'<p>No open reports.</p>';for(const button of box.querySelectorAll('button'))button.onclick=safe(async()=>{const id=button.dataset.inspect||button.dataset.hide||button.dataset.resolve,r=result.reports.find(x=>x.id===id);if(button.dataset.inspect)return detail(r.kind,r.item_id);if(button.dataset.hide)await api(`/v1/community/${r.kind}/${r.item_id}/hide`,{method:'POST',data:{}});await api(`/v1/community/reports/${id}`,{method:'POST',data:{}});await moderation();});}
 if(new URL(location.href).searchParams.has('lobby')){await lobbyUI({root:frame('Live lobbies'),user,api,startRace,close,currentAttempt,stopRace});return;}
 if(new URL(location.href).searchParams.has('competition')){await competitionUI({root:frame('Competitions'),api,startRace,close});return;}
 const shared=new URL(location.href).searchParams.get('community');if(/^(level|set):[a-zA-Z0-9-]+$/.test(shared||'')){const [kind,id]=shared.split(':');await detail(kind,id);}else await browse();
}
