const topics=[
 ['Switches, levers & timers','PRESS / SET buttons latch once. Levers marked ↔ can turn on and off: leave their circle before returning. Timers count down after activation. Letters match gates; the objective bar shows what the exit still needs.'],
 ['Wall jumps','Touch a wall, steer away and jump to kick off. Falling against a wall slows your slide. There is no mid-air double jump.'],
 ['Lasers & projectiles','Amber warns before a laser fires. Cross when dark or find its shutdown switch. Cover stops straight shots; slow heat rockets can be lured into walls. Tracking eyes need a clear sight line before firing.'],
 ['Moving and crumbling decks','Jump through decks from below. Moving decks pause at each end. Crumbling decks break after landing; Easy and Medium rebuild them after 3.5 seconds. Hard and Nightmare do not.'],
 ['Traps & alarms','T labels connect pressure plates to traps. Step off and return to trigger a reset plate again. Alarm letters show which circuit wakes a hazard group. Switching a device off does not remove shots already flying.'],
 ['Equipment & gold','Buy charges in the shop, then press 1–5 or click equipment to use one. Helpers are optional. Gold is banked only on completing a stage; cyan-ring pickups offer a first-time bonus.'],
 ['Difficulty & progress','Choose difficulty in Options. Easy slows hazards and helps jumping. Hard speeds hazard cycles. Nightmare adds a seeded ghost hunter. Completed stages can be replayed; progress saves in this browser.'],
];
export function helpMarkup(){return `<h2>Your next escape.</h2><div class="help-basics"><p><strong>Move:</strong> ← → or A / D. <strong>Jump:</strong> Space, W, or ↑.</p><p><strong>Goal:</strong> activate the required circuits, then reach the exit. Gold is optional.</p><p><strong>Enter:</strong> start, resume, retry, or continue. <strong>R:</strong> restart. <strong>P / Escape:</strong> pause.</p><p><strong>M:</strong> small map → paused full-room survey → hidden.</p></div><div class="help-topics">${topics.map(([title,body])=>`<details><summary>${title}</summary><p>${body}</p></details>`).join('')}</div>`;}
