import {api} from './online.js';import {replayViewer} from './replay-viewer.js';import {RULESET} from './replay.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function createHighscores({root,edition,storage,onSignin}){
 const dialog=document.createElement('dialog');dialog.className='online-dialog';dialog.innerHTML='<button class="modal-close" aria-label="Close highscores">×</button><div class="online-content"></div>';root.append(dialog);const content=dialog.querySelector('.online-content');let stopReplay=null;dialog.querySelector('button').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{stopReplay?.();stopReplay=null;});
 function show(){stopReplay?.();stopReplay=null;if(!dialog.open)dialog.showModal();}
 async function browse(stage=0,difficulty='medium',assistance='itemFree'){show();content.innerHTML=`<h2>Verified highscores</h2><p>Separate ladders by difficulty and helpers. Input replays are checked against the game rules. ${edition==='kids'?'Nicknames come from a friendly preset list.':'Sharing scores requires an invited account.'}</p><form><label>Stage<select name="stage">${Array.from({length:99},(_,i)=>`<option value="${i}" ${stage===i?'selected':''}>${i+1}</option>`).join('')}</select></label><label>Difficulty<select name="difficulty">${['easy','medium','hard','nightmare'].map(v=>`<option ${v===difficulty?'selected':''}>${v}</option>`).join('')}</select></label><label>Helpers<select name="assistance"><option value="itemFree" ${assistance==='itemFree'?'selected':''}>Without helpers</option><option value="assisted" ${assistance==='assisted'?'selected':''}>Assisted</option></select></label><button class="secondary">Show scores</button></form><p role="status">Loading…</p><ol id="online-scores"></ol>`;content.querySelector('form').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));browse(+data.stage,data.difficulty,data.assistance);};try{const result=await api(`/v1/scores?edition=${edition}&stage=${stage}&difficulty=${difficulty}&assistance=${assistance}`);content.querySelector('[role=status]').textContent=result.results.length?'':'No verified runs in this category yet.';content.querySelector('ol').innerHTML=result.results.map(r=>`<li>${esc(r.name)} — ${r.time.toFixed(2)}s <button class="text-button" data-watch="${r.id}">Watch replay</button></li>`).join('');for(const b of content.querySelectorAll('[data-watch]'))b.onclick=async()=>{try{const record=await api(`/v1/scores/${b.dataset.watch}/replay`);if(!dialog.open)return;stopReplay=replayViewer(content,record);}catch(error){content.querySelector('[role=status]').textContent=error.message;}};}catch(error){content.querySelector('[role=status]').textContent=error.message;}}
 async function share(run){show();content.innerHTML=`<h2>Share this verified run</h2><p>Stage ${run.stage+1} · ${run.difficulty}. Upload only this run’s input replay and category. ${edition==='kids'?'Your public nickname is generated from a preset list.':'Your account name and replay will be public on the highscore board.'} Your local career stays in this browser.</p><button class="primary" id="upload-run">Verify and share</button><p role="status"></p>`;content.querySelector('button').onclick=async e=>{e.currentTarget.disabled=true;const status=content.querySelector('[role=status]');status.textContent='Verifying…';try{let guestToken;if(edition==='kids'){guestToken=storage.getItem('score-token');if(!guestToken){const guest=await api('/v1/scores/guest',{method:'POST',data:{}});guestToken=guest.token;storage.setItem('score-token',guestToken);}}const result=await api('/v1/scores',{method:'POST',data:{...run,edition,guestToken}});status.textContent=`Verified: ${result.name} · ${result.time.toFixed(2)}s · ${result.assistance}.`;const button=document.createElement('button');button.className='secondary';button.textContent='View leaderboard';button.onclick=()=>browse(run.stage,run.difficulty,result.assistance);content.append(button);}catch(error){status.textContent=error.message;if(error.status===401){if(edition==='kids'){storage.removeItem('score-token');status.textContent='Your nickname expired. Press Verify and share to create another.';}else{const sign=document.createElement('button');sign.className='secondary';sign.textContent='Sign in, then share again';sign.onclick=()=>{dialog.close();onSignin();};content.append(sign);}}content.querySelector('#upload-run').disabled=false;}};}
 return {browse,share};
}
