const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export async function lobbyUI({root,user,api,startRace,close,currentAttempt=()=>null,stopRace=()=>{}}){
 let selected=null,entered=false,timer=null,pollBusy=false;const alive=()=>root.isConnected&&root.closest('dialog')?.open;const status=message=>{const e=root.querySelector('[role=status]');if(e)e.textContent=message;};const safe=fn=>async e=>{try{await fn(e);}catch(error){status(error.message);}};
 async function list(){selected=null;const result=await api('/v1/lobbies');root.innerHTML=`<h3>Live races</h3><p>2–8 invited players. Everyone readies up, then the host starts a five-second countdown. All racers share the server clock and frozen rules. Disconnects do not pause the clock.</p><p role="status"></p><button class="secondary" id="create-lobby">Create lobby</button><div class="community-list">${result.lobbies.map(l=>`<article><h3>${esc(l.name)}</h3><small>${l.state}</small><button class="secondary" data-room="${l.id}">Open room</button></article>`).join('')}</div>`;root.querySelector('#create-lobby').onclick=safe(create);for(const b of root.querySelectorAll('[data-room]'))b.onclick=safe(()=>room(b.dataset.room));}
 async function create(){selected=null;const events=await api('/v1/competitions');root.innerHTML=`<h3>Create a live lobby</h3><p>The selected event supplies frozen levels, difficulty, helpers and duration. This lobby gets its own synchronized start.</p><form><label>Lobby name<input name="name" maxlength="60" required></label><label>Event template<select name="competitionId">${events.events.map(e=>`<option value="${e.id}">${esc(e.name)} · ${e.rules.difficulty}</option>`).join('')}</select></label><button class="primary" ${events.events.length?'':'disabled'}>Create room</button></form><p role="status">${events.events.length?'':'Create a competition from a published set first.'}</p>`;root.querySelector('form').onsubmit=safe(async e=>{e.preventDefault();const result=await api('/v1/lobbies',{method:'POST',data:Object.fromEntries(new FormData(e.currentTarget))});await room(result.id);});}
 async function room(id){selected=id;entered=false;await poll(id);}
 async function poll(id){clearTimeout(timer);if(!alive()||selected!==id||pollBusy)return;pollBusy=true;try{
 const state=await api(`/v1/lobbies/${id}`);if(!alive()||selected!==id)return;
 root.innerHTML=`<h3>${esc(state.name)}</h3><p>${state.state==='countdown'?`Starts in ${Math.max(0,Math.ceil((state.countdown-state.serverTime)/1000))}s`:state.state.toUpperCase()}</p><label>Room link<input readonly value="${esc(location.origin+'/?lobby='+id)}"></label><ul>${state.members.map(m=>`<li>${esc(m.name)}${m.id===state.host_id?' · host':''} · ${m.online?'online':'reconnecting'} · ${state.state==='waiting'||state.state==='countdown'?(m.ready?'ready':'not ready'):`${m.progress} levels · ${m.status}${m.totalMs?' · '+(m.totalMs/1000).toFixed(2)+'s':''}`}</li>`).join('')}</ul><div class="community-actions">${!state.me&&state.state==='waiting'?'<button class="primary" data-lobby="join">Join room</button>':''}${state.me&&state.state==='waiting'?`<button class="primary" data-lobby="ready">${state.me.ready?'Not ready':'Ready'}</button>`:''}${state.host_id===user.id&&state.state==='waiting'?'<button class="secondary" data-lobby="start">Start countdown</button>':''}${state.race?.attempt.status==='active'&&state.race.attempt.id===currentAttempt()?'<button class="primary" id="resume-room-race">Resume race</button>':''}${state.me&&!state.me.forfeit?'<button class="secondary" data-lobby="leave">Leave / forfeit</button>':''}${state.host_id===user.id||user.role==='admin'?'<button class="secondary" data-lobby="close">Close room</button>':''}<button class="secondary" id="lobby-list">All rooms</button></div><p role="status"></p>`;
 for(const b of root.querySelectorAll('[data-lobby]'))b.onclick=safe(async()=>{const action=b.dataset.lobby;await api(`/v1/lobbies/${id}/${action}`,{method:'POST',data:action==='ready'?{ready:!state.me.ready}:{}});if(action==='close'||action==='leave'){stopRace(state.me?.attemptId);await list();}else await poll(id);});root.querySelector('#lobby-list').onclick=safe(list);const resume=root.querySelector('#resume-room-race');if(resume)resume.onclick=()=>{close();startRace(state.race);};
 if(state.state==='running'&&state.race?.attempt.status==='active'&&state.race.attempt.id!==currentAttempt()&&!entered){entered=true;selected=null;close();startRace(state.race);return;}
 if(['waiting','countdown','running'].includes(state.state))timer=setTimeout(()=>poll(id),state.state==='countdown'?Math.max(50,Math.min(1000,state.countdown-state.serverTime+20)):3000);
 }catch(error){status(error.message);if(alive()&&selected===id)timer=setTimeout(()=>poll(id),5000);}finally{pollBusy=false;}}
 const id=new URL(location.href).searchParams.get('lobby');if(id&&/^[a-f0-9-]{36}$/.test(id))await room(id);else await list();
}
