import {communityUI} from './community-ui.js';
import {IS_KIDS} from './edition.js';import {validateLevel} from './levels.js';import {analyzeLevel,blueprintFromLevel} from './level-analysis.js';
export const API_URL=import.meta.env?.VITE_API_URL||'https://api.bnb.minizap.online';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export async function api(path,{method='GET',data}={}){const response=await fetch(API_URL+path,{method,credentials:'include',headers:method==='GET'?{}:{'Content-Type':'application/json','X-BNB-Client':'1'},...(data?{body:JSON.stringify(data)}:{}),signal:AbortSignal.timeout(80000)});const result=await response.json();if(!response.ok)throw Error(result.error||'Online service is unavailable.');return result;}
export function createOnlineWorkshop({root,onDraft,thumbnail,getDraft,onPlay}){
 if(IS_KIDS)return {open(){}};
 const dialog=document.createElement('dialog');dialog.className='online-dialog';dialog.innerHTML='<button class="modal-close" aria-label="Close online workshop">×</button><div class="online-content"></div>';root.append(dialog);const content=dialog.querySelector('.online-content');let user=null,candidate=null,mode='ai';
 dialog.querySelector('.modal-close').onclick=()=>dialog.close();
 const status=message=>{const el=content.querySelector('[role=status]');if(el)el.textContent=message;};
 function auth(){content.innerHTML=`<h2>Online workshop</h2><p>Invite-only access. Your offline career stays in this browser.</p><form id="online-auth"><label>Account name<input name="name" autocomplete="username" minlength="3" maxlength="24" required></label><label>Password<input name="password" type="password" autocomplete="current-password" minlength="12" maxlength="128" required></label><label>Invitation (new accounts only)<input name="invite" autocomplete="off" maxlength="100"></label><div><button class="primary" name="login" type="submit">Sign in</button><button class="secondary" name="register" type="submit">Create invited account</button></div></form><p role="status"></p>`;
 content.querySelector('form').onsubmit=async e=>{e.preventDefault();const input=Object.fromEntries(new FormData(e.currentTarget));for(const b of e.currentTarget.querySelectorAll('button'))b.disabled=true;try{const result=await api(e.submitter.name==='register'?'/v1/register':'/v1/login',{method:'POST',data:input});user=result.user;await signedIn();}catch(error){status(error.message);for(const b of content.querySelectorAll('button'))b.disabled=false;}};
 }
 async function signedIn(){if(mode==='community')return communityUI({root:content,user,api,getDraft,onPlay,onDraft,close:()=>dialog.close(),ai:()=>{mode='ai';return workshop();}});return workshop();}
 async function workshop(){const allowance=await api('/v1/ai/config');content.innerHTML=`<h2>Create a puzzle</h2><p>Signed in as ${esc(user.name)}. <button class="text-button" id="online-logout">Sign out</button></p><p>Free model · estimated $0 per request · total daily cap $${allowance.dailyDollars.toFixed(2)}. Used $${allowance.spentDollars.toFixed(4)} today; ${allowance.userRequests}/${allowance.userDailyRequests} requests for your account.</p><form id="ai-form"><label>Model<select name="model">${allowance.models.map(model=>`<option>${esc(model)}</option>`).join('')}</select></label><label>Design brief<textarea name="prompt" minlength="10" maxlength="1500" rows="5" required placeholder="A hard wall-jump route with two switches, a safe return path, and optional gold above the exit…"></textarea></label><p>First version: 32 × 18 rooms with walls, switches, gates, gold, spikes and moving saws. Describe the lesson, route alternatives, difficulty, and recovery space. Drafts need playtesting.</p><label><span><input type="checkbox" name="revise"> Revise my current 32 × 18 draft</span></label><button class="primary" ${allowance.enabled?'':'disabled'}>Generate one draft</button></form><p role="status"></p><div id="ai-result"></div>`;
 content.querySelector('#online-logout').onclick=async()=>{try{await api('/v1/logout',{method:'POST'});user=null;auth();}catch(error){status(error.message);}};
 content.querySelector('#ai-form').onsubmit=async e=>{e.preventDefault();const button=e.currentTarget.querySelector('button');button.disabled=true;candidate=null;content.querySelector('#ai-result').replaceChildren();status('Creating one draft. This may take a minute; no automatic retries.');try{const data={...Object.fromEntries(new FormData(e.currentTarget)),requestKey:crypto.randomUUID()};if(data.revise){blueprintFromLevel(getDraft());data.level=getDraft();}delete data.revise;const job=await api('/v1/ai/generate',{method:'POST',data});if(job.status!=='done')throw Error(job.error||'Generation is still running. Try reopening later.');candidate=validateLevel(job.result.level);const analysis=analyzeLevel(candidate);status(`Draft ready · ${job.tokens} tokens · $${job.costDollars.toFixed(4)} · ${analysis.status.toUpperCase()}`);content.querySelector('#ai-result').innerHTML=`${thumbnail(candidate)}<h3>${esc(candidate.name)}</h3><p>${esc(job.result.rationale)}</p><p>${esc(analysis.reasons.join(' '))}</p><button class="primary" id="apply-ai">Load draft in editor</button><p>Your previous draft will be downloaded as a backup. Nothing is published.</p>`;content.querySelector('#apply-ai').onclick=()=>{onDraft(candidate);dialog.close();};}catch(error){status(error.message);}finally{button.disabled=false;}};
 }
 return {async open(destination='ai'){mode=destination;dialog.showModal();content.innerHTML='<h2>Online workshop</h2><p>Connecting…</p>';try{user=(await api('/v1/me')).user;if(user)await signedIn();else auth();}catch(error){content.innerHTML=`<h2>Online workshop unavailable</h2><p>${esc(error.message)}</p><p>The offline editor, campaign and JSON import/export remain available.</p>`;}}};
}
