import {Game} from './engine.js';import {campaignLevel,W,H} from './levels.js';import {bossArena} from './bosses.js';import {renderGame} from './renderer.js';import {RULESET,TICK_RATE,validateTape} from './replay.js';
export function replayViewer(root,record){
 if(record.ruleset!==RULESET)throw Error('This replay needs another game rules version.');for(const tape of record.replays)validateTape(tape);
 root.innerHTML='<h3>Verified replay</h3><canvas class="replay-canvas" aria-label="Replay playback"></canvas><div><button class="secondary" data-replay-pause>Pause playback</button><button class="secondary" data-replay-restart>Restart</button></div><p data-replay-status></p>';
 const canvas=root.querySelector('canvas'),ctx=canvas.getContext('2d');const g=Object.create(Game.prototype);g.keys=new Set();g.difficulty=record.difficulty;g.recordReplay=false;g.reducedMotion=true;g.ctx=ctx;g.canvas=canvas;g.cb={hud(){},sound(){},gold(){},switch(){},win(){},dying(){},dead(){}};g.render=()=>{};
 let phase=0,action=0,frame=0,paused=false,last=0,accumulator=0,raf,closed=false;
 function load(){const effects={...g.effects};g.load(phase?bossArena(record.stage):campaignLevel(record.stage),record.stage+1);if(phase)g.effects=effects;g.start();action=0;frame=0;}
 function tick(){const tape=record.replays[phase],a=tape.actions[action];if(!a){if(phase+1<record.replays.length){phase++;load();}else paused=true;return;}g.keys.clear();if(a.dir)g.keys.add(a.dir>0?'ArrowRight':'ArrowLeft');if(a.clear)g.jumpBuffer=0;if(a.jump)g.jumpBuffer=.14;for(const id of a.helpers)g.activate(id);g.update(1/TICK_RATE);if(++frame>=a.frames){frame=0;action++;}}
 function draw(t){if(closed)return;const dt=Math.min((t-last)/1000||0,.1);last=t;if(!paused){accumulator+=dt;while(accumulator>=1/TICK_RATE){accumulator-=1/TICK_RATE;tick();}}const r=canvas.getBoundingClientRect(),w=Math.max(1,Math.round(r.width*(devicePixelRatio||1))),h=Math.max(1,Math.round(r.height*(devicePixelRatio||1)));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}ctx.setTransform(w/W,0,0,h/H,0,0);renderGame(g);root.querySelector('[data-replay-status]').textContent=`Part ${phase+1}/${record.replays.length} · ${g.elapsed.toFixed(2)}s · ${paused?'paused / finished':'playing'}`;raf=requestAnimationFrame(draw);}
 root.querySelector('[data-replay-pause]').onclick=()=>{paused=!paused;};root.querySelector('[data-replay-restart]').onclick=()=>{phase=0;load();paused=false;accumulator=0;};load();raf=requestAnimationFrame(draw);return ()=>{closed=true;cancelAnimationFrame(raf);};
}
