import {validateLevel} from './levels.js';import {bossArena} from './bosses.js';
export const ARENA_ZONES=[{id:'guardian',name:'Guardian & movement',x:3,y:16},{id:'circuits',name:'Buttons, gates & timers',x:32,y:16},{id:'projectiles',name:'Beams, shots & following rockets',x:65,y:16},{id:'decks',name:'Moving & crumbling platforms',x:4,y:34},{id:'traps',name:'Pressure pads & alarms',x:39,y:34},{id:'finish',name:'Exit',x:89,y:34}];
export function testArena(zone='guardian'){
 const tiles=[];for(let x=0;x<96;x++){tiles.push({x,y:35,type:'solid'});if(x<88||x>91)tiles.push({x,y:17,type:'solid'});}for(let y=0;y<35;y++){if(y!==17)tiles.push({x:0,y,type:'solid'},{x:95,y,type:'solid'});}
 for(const x of [7,8])for(const y of [33,34])tiles.push({x,y,type:'solid'});
 tiles.push({x:35,y:16,type:'spike'},{x:36,y:16,type:'spike'},{x:40,y:15,type:'drone'});
 for(let y=13;y<17;y++)tiles.push({x:75,y,type:'solid'});
 const spawn=ARENA_ZONES.find(z=>z.id===zone)||ARENA_ZONES[0];
 const level=validateLevel({version:3,name:'Feature test arena',width:96,height:36,time:300,spawn:{x:spawn.x,y:spawn.y},exit:{x:93,y:34},tiles,coins:[{x:8,y:16},{x:37,y:13},{x:48,y:16},{x:18,y:32}],switches:[{id:'A',x:33,y:16},{id:'B',x:50,y:16,mode:'toggle',initial:false},{id:'C',x:58,y:16,mode:'timed',duration:8},{id:'D',x:60,y:34},{id:'E',x:65,y:34,mode:'toggle',initial:false}],gates:[{switchId:'A',x:46,y:14,w:1,h:3},{switchId:'B',x:54,y:14,w:1,h:3,states:{B:false}},{switchId:'C',x:62,y:14,w:1,h:3},{switchId:'E',x:80,y:32,w:1,h:3,states:{E:true,D:false}}],exitRequires:[],devices:[{type:'laser',x:66,y:10,dir:'down',length:6,period:3,on:1,phase:0,offSwitch:'A'},{type:'turret',x:70,y:12,dir:'right',period:3,phase:0,speed:220,projectile:'straight'},{type:'turret',x:79,y:12,dir:'left',period:4,phase:0,speed:120,projectile:'homing'},{type:'laser',x:72,y:30,dir:'left',length:6,period:3,on:1,phase:0,offSwitch:'D',alarm:{switchId:'E',on:true,delay:1.2}}],sentries:[{x:85,y:10,range:12,lock:1,cooldown:2,speed:220,offSwitch:'D'}],platforms:[{x:10,y:31,toX:15,toY:31,w:3,period:4,phase:0},{x:22,y:33,toX:22,toY:25,w:3,period:5,phase:0}],crumbles:[{x:30,y:30,w:4,delay:.8}],traps:[{type:'spikes',x:40,y:34,tx:44,ty:34,w:3,delay:.7,active:1,cooldown:3},{type:'dart',x:50,y:34,tx:55,ty:31,dir:'left',speed:200,delay:.6,active:1,cooldown:3,offSwitch:'D',alarm:{switchId:'E',on:true,delay:1.2}}]});
 return {...level,testArena:true,boss:bossArena(29).boss,skill:'Choose a station. Try every tool.',lesson:'One shared arena: guardian, all obstacle families, circuit modes, alarms and both projectile types. Helpers are free. Pick Nightmare in Options to test the seeded visitor, then reopen this arena.'};
}
